# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-733328-lygdebug/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7s25csga225-1
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl 
    set rt::defaultWorkLibName work
    rt::set_parameter defaultVhdlWorkLib work

    rt::set_parameter loadVhdl2008Libs false
    rt::set_parameter loadVhdl2019Libs false
    rt::set_parameter deferParseUntilElab true
    rt::set_parameter sortHdlCommandLine true
    rt::set_parameter singleFileBasedDefaultNettype false
    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog -include {
    /home/lyg/PA/ysyx-workbench/npc/rv64/vsrc/include
    /home/lyg/AMD/2025.2/2025.2/data/rsb/busdef
  } -define SYNTHESIS=1 {
      /home/lyg/PA/ysyx-workbench/npc/rv64/vsrc/include/define.v
      /home/lyg/PA/ysyx-workbench/npc/rv64/vsrc/execute/ALU.v
      /home/lyg/PA/ysyx-workbench/npc/rv64/vsrc/execute/CompareUnit.v
      /home/lyg/PA/ysyx-workbench/npc/rv64/vsrc/core/CsrFile.v
      /home/lyg/PA/ysyx-workbench/npc/rv64/vsrc/decode/DecodeStage.v
      /home/lyg/PA/ysyx-workbench/npc/rv64/vsrc/decode/DecodeUnit.v
      /home/lyg/PA/ysyx-workbench/npc/rv64/vsrc/decode/ImmGen.v
      /home/lyg/PA/ysyx-workbench/npc/rv64/vsrc/memory/LSU.v
      /home/lyg/PA/ysyx-workbench/npc/rv64/vsrc/memory/LSUControl.v
      /home/lyg/PA/ysyx-workbench/npc/rv64/vsrc/memory/LSUDataPath.v
      /home/lyg/PA/ysyx-workbench/npc/rv64/vsrc/ooo/backend/OooAluCoreSlice.v
      /home/lyg/PA/ysyx-workbench/npc/rv64/vsrc/ooo/backend/OooAluDecodeBackend.v
      /home/lyg/PA/ysyx-workbench/npc/rv64/vsrc/ooo/frontend/OooAluFetchCore.v
      /home/lyg/PA/ysyx-workbench/npc/rv64/vsrc/ooo/regfile/OooArchRegFile.v
      /home/lyg/PA/ysyx-workbench/npc/rv64/vsrc/frontend/OooBranchDirectionPredictor.v
      /home/lyg/PA/ysyx-workbench/npc/rv64/vsrc/frontend/OooBranchTargetCache.v
      /home/lyg/PA/ysyx-workbench/npc/rv64/vsrc/ooo/rename/OooBusyTable.v
      /home/lyg/PA/ysyx-workbench/npc/rv64/vsrc/cache/OooDataWordCache.v
      /home/lyg/PA/ysyx-workbench/npc/rv64/vsrc/ooo/backend/OooDispatchBackend.v
      /home/lyg/PA/ysyx-workbench/npc/rv64/vsrc/core/OooFetchAxiBridge.v
      /home/lyg/PA/ysyx-workbench/npc/rv64/vsrc/cache/OooFetchPacketCache.v
      /home/lyg/PA/ysyx-workbench/npc/rv64/vsrc/ooo/frontend/OooFpDecode.v
      /home/lyg/PA/ysyx-workbench/npc/rv64/vsrc/ooo/rename/OooFreeList.v
      /home/lyg/PA/ysyx-workbench/npc/rv64/vsrc/ooo/backend/OooIntBackend.v
      /home/lyg/PA/ysyx-workbench/npc/rv64/vsrc/ooo/issue/OooIntIssueQueue.v
      /home/lyg/PA/ysyx-workbench/npc/rv64/vsrc/frontend/OooJalrBtb.v
      /home/lyg/PA/ysyx-workbench/npc/rv64/vsrc/core/OooMemAxiBridge.v
      /home/lyg/PA/ysyx-workbench/npc/rv64/vsrc/ooo/regfile/OooPhysRegFile.v
      /home/lyg/PA/ysyx-workbench/npc/rv64/vsrc/ooo/rename/OooRenameMap.v
      /home/lyg/PA/ysyx-workbench/npc/rv64/vsrc/ooo/commit/OooRob.v
      /home/lyg/PA/ysyx-workbench/npc/rv64/vsrc/ooo/frontend/OooRvcDecompressor.v
      /home/lyg/PA/ysyx-workbench/npc/rv64/vsrc/common/OooSv39Tlb.v
      /home/lyg/PA/ysyx-workbench/npc/rv64/vsrc/writeback/WBU.v
      /home/lyg/PA/ysyx-workbench/npc/rv64/vsrc/core/NpcCoreTop.v
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList ./.Xil/Vivado-733328-lygdebug/realtime/NpcCoreTop_synth.xdc
    rt::sdcChecksum
    set rt::top NpcCoreTop
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::ioInsertion false
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: out_of_context
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-733328-lygdebug/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
uplevel #0 { 
   if {[info exists rt::doParallel] && $rt::doParallel} {
     rt::async_wait "asyncParallelOpen"
     rt::parallel_close
   }
   $rt::db resetHdlParse
   set hsKey [rt::get_parameter helper_shm_key] 
   if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
      $rt::db killSynthHelper $hsKey
   } 
   source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  }
 return -code "error" $rt::result
}
