#ifndef __RISCV32_INSTRUCTION_H__
#define __RISCV32_INSTRUCTION_H__

#include <common.h>

/*
 * RV32 指令先被译成手册助记符，再进入唯一执行入口。
 * 原始编码只服务于非法指令 tval 和尚未迁移的扩展适配器。
 */
typedef enum {
  RV32_INSTRUCTION_CLASS_ILLEGAL = 0,
  RV32_INSTRUCTION_CLASS_INTEGER_IMMEDIATE,
  RV32_INSTRUCTION_CLASS_INTEGER_REGISTER,
  RV32_INSTRUCTION_CLASS_MULTIPLY_DIVIDE,
  RV32_INSTRUCTION_CLASS_BIT_MANIPULATION,
  RV32_INSTRUCTION_CLASS_LOAD,
  RV32_INSTRUCTION_CLASS_STORE,
  RV32_INSTRUCTION_CLASS_BRANCH,
  RV32_INSTRUCTION_CLASS_JUMP,
  RV32_INSTRUCTION_CLASS_UPPER_IMMEDIATE,
  RV32_INSTRUCTION_CLASS_MEMORY_ORDERING,
  RV32_INSTRUCTION_CLASS_EXTENSION_ADAPTER,
} Rv32InstructionClass;

typedef enum {
  RV32_OPERATION_ILLEGAL_INSTRUCTION = 0,

  RV32_OPERATION_ADDI,
  RV32_OPERATION_SLTI,
  RV32_OPERATION_SLTIU,
  RV32_OPERATION_XORI,
  RV32_OPERATION_ORI,
  RV32_OPERATION_ANDI,
  RV32_OPERATION_SLLI,
  RV32_OPERATION_SRLI,
  RV32_OPERATION_SRAI,

  RV32_OPERATION_ADD,
  RV32_OPERATION_SUB,
  RV32_OPERATION_SLL,
  RV32_OPERATION_SLT,
  RV32_OPERATION_SLTU,
  RV32_OPERATION_XOR,
  RV32_OPERATION_SRL,
  RV32_OPERATION_SRA,
  RV32_OPERATION_OR,
  RV32_OPERATION_AND,

  RV32_OPERATION_MUL,
  RV32_OPERATION_MULH,
  RV32_OPERATION_MULHSU,
  RV32_OPERATION_MULHU,
  RV32_OPERATION_DIV,
  RV32_OPERATION_DIVU,
  RV32_OPERATION_REM,
  RV32_OPERATION_REMU,

  /* Zba 地址生成。 */
  RV32_OPERATION_SH1ADD,
  RV32_OPERATION_SH2ADD,
  RV32_OPERATION_SH3ADD,

  /* Zbb 基础位运算。 */
  RV32_OPERATION_ANDN,
  RV32_OPERATION_ORN,
  RV32_OPERATION_XNOR,
  RV32_OPERATION_CLZ,
  RV32_OPERATION_CTZ,
  RV32_OPERATION_CPOP,
  RV32_OPERATION_SEXT_B,
  RV32_OPERATION_SEXT_H,
  RV32_OPERATION_ROL,
  RV32_OPERATION_ROR,
  RV32_OPERATION_RORI,
  RV32_OPERATION_MIN,
  RV32_OPERATION_MINU,
  RV32_OPERATION_MAX,
  RV32_OPERATION_MAXU,
  RV32_OPERATION_ORC_B,
  RV32_OPERATION_REV8,
  RV32_OPERATION_ZEXT_H,

  /* Zbc 无进位乘法。 */
  RV32_OPERATION_CLMUL,
  RV32_OPERATION_CLMULR,
  RV32_OPERATION_CLMULH,

  /* Zbs 单比特运算。 */
  RV32_OPERATION_BSET,
  RV32_OPERATION_BSETI,
  RV32_OPERATION_BCLR,
  RV32_OPERATION_BCLRI,
  RV32_OPERATION_BEXT,
  RV32_OPERATION_BEXTI,
  RV32_OPERATION_BINV,
  RV32_OPERATION_BINVI,

  RV32_OPERATION_LB,
  RV32_OPERATION_LH,
  RV32_OPERATION_LW,
  RV32_OPERATION_LBU,
  RV32_OPERATION_LHU,
  RV32_OPERATION_SB,
  RV32_OPERATION_SH,
  RV32_OPERATION_SW,

  RV32_OPERATION_BEQ,
  RV32_OPERATION_BNE,
  RV32_OPERATION_BLT,
  RV32_OPERATION_BGE,
  RV32_OPERATION_BLTU,
  RV32_OPERATION_BGEU,
  RV32_OPERATION_JAL,
  RV32_OPERATION_JALR,
  RV32_OPERATION_LUI,
  RV32_OPERATION_AUIPC,
  RV32_OPERATION_FENCE,
  RV32_OPERATION_FENCE_I,

  RV32_OPERATION_COMPRESSED_ADAPTER,
  RV32_OPERATION_FLOATING_LOAD_ADAPTER,
  RV32_OPERATION_FLOATING_STORE_ADAPTER,
  RV32_OPERATION_ATOMIC_ADAPTER,
  RV32_OPERATION_SYSTEM_ADAPTER,
} Rv32Operation;

typedef enum {
  RV32_X_OPERAND_NONE = 0,
  RV32_X_OPERAND_RD = 1u << 0,
  RV32_X_OPERAND_RS1 = 1u << 1,
  RV32_X_OPERAND_RS2 = 1u << 2,
} Rv32XRegisterOperand;

typedef struct {
  uint32_t encoding;
  word_t immediate;
  Rv32InstructionClass instruction_class;
  Rv32Operation operation;
  uint8_t length;
  uint8_t rd;
  uint8_t rs1;
  uint8_t rs2;
  uint8_t x_register_operands;
} Rv32DecodedInstruction;

#endif
