`ifndef R64_PLATFORM_MAP_VH
`define R64_PLATFORM_MAP_VH
`include "define.v"
// Preserve the existing port order; the unused GPIO slot now hosts the real
// Goldfish RTC required by the platform regression. A zero mask is not a
// matching catch-all: the native fabric produces DECERR internally on misses.
`define R64_RTC_BASE 64'h0000000010003000
`define R64_RTC_MASK 64'hfffffffffffff000
`define R64_PLATFORM_SLAVES 16
`define R64_PLATFORM_BASE { \
  `NPC_AXI_DEFAULT_BASE, `NPC_AXI_CHIPLINK_MEM_BASE, \
  `NPC_AXI_SDRAM_BASE, `NPC_AXI_LEGACY_MMIO_BASE, \
  `NPC_AXI_PSRAM_BASE, `NPC_AXI_CHIPLINK_MMIO_BASE, \
  `NPC_AXI_FLASH_BASE, `NPC_AXI_VGA_BASE, \
  `NPC_AXI_MROM_BASE, `NPC_AXI_PS2_BASE, \
  `R64_RTC_BASE, `NPC_AXI_VIRTIO_BLK_BASE, \
  `NPC_AXI_UART_BASE, `NPC_AXI_RESET_SYSCON_BASE, \
  `NPC_AXI_PLIC_BASE, `NPC_AXI_CLINT_BASE }
`define R64_PLATFORM_MASK { \
  `NPC_AXI_DEFAULT_MASK, `NPC_AXI_CHIPLINK_MEM_MASK, \
  `NPC_AXI_SDRAM_MASK, `NPC_AXI_LEGACY_MMIO_MASK, \
  `NPC_AXI_PSRAM_MASK, `NPC_AXI_CHIPLINK_MMIO_MASK, \
  `NPC_AXI_FLASH_MASK, `NPC_AXI_VGA_MASK, \
  `NPC_AXI_MROM_MASK, `NPC_AXI_PS2_MASK, \
  `R64_RTC_MASK, `NPC_AXI_VIRTIO_BLK_MASK, \
  `NPC_AXI_UART_MASK, `NPC_AXI_RESET_SYSCON_MASK, \
  `NPC_AXI_PLIC_MASK, `NPC_AXI_CLINT_MASK }
`define R64_PLATFORM_MEMORY 16'h6a80
`define R64_PLATFORM_EXECUTABLE 16'h6a80
`endif
