// Native CPU and AXI platform. External ports are real AXI-Lite endpoints.
module R64SystemTop(
 input clk_i,
 input rst_i,
 input run_i,
 input dma_invalidate_i,
 output tensor_cmd_valid_o,
 input tensor_cmd_ready_i,
 output [8:0] tensor_cmd_tag_o,
 output [63:0] tensor_cmd_o,
 output [63:0] tensor_operand_o,
 output tensor_pair_o,
 output [7:0] tensor_class_o,
 input tensor_terminal_valid_i,
 output tensor_terminal_ready_o,
 input [8:0] tensor_terminal_tag_i,
 input tensor_error_i,
 input [7:0] tensor_error_code_i,
 input [1:0] trace_ready_i,
 output [1:0] trace_valid_o,
 output [127:0] trace_pc_o,
 output [127:0] trace_raw_o,
 output [127:0] trace_npc_o,
 output [127:0] trace_data_o,
 output [7:0] trace_length_o,
 output [1:0] trace_rd_write_o,
 output [1:0] trace_rd_fp_o,
 output [9:0] trace_rd_arch_o,
 output [9:0] trace_fflags_o,
 output [15:0] trace_kind_o,
 output trap_valid_o,
 output trap_interrupt_o,
 output [5:0] trap_cause_o,
 output [63:0] trap_pc_o,
 output [63:0] trap_tval_o,
 output [63:0] trap_raw_o,
 output [63:0] trap_target_o,
 output [3:0] trap_length_o,
 output [1:0] privilege_o,
 output [63:0] mstatus_o,
 output [63:0] satp_o,
 output [5:0] rob_count_o,
 output [3:0] ext_arvalid_o,
 input [3:0] ext_arready_i,
 output [255:0] ext_araddr_o,
 output [11:0] ext_arsize_o,
 output [11:0] ext_arprot_o,
 input [3:0] ext_rvalid_i,
 output [3:0] ext_rready_o,
 input [255:0] ext_rdata_i,
 input [7:0] ext_rresp_i,
 output [3:0] ext_awvalid_o,
 input [3:0] ext_awready_i,
 output [255:0] ext_awaddr_o,
 output [11:0] ext_awsize_o,
 output [3:0] ext_wvalid_o,
 input [3:0] ext_wready_i,
 output [255:0] ext_wdata_o,
 output [31:0] ext_wstrb_o,
 input [3:0] ext_bvalid_i,
 output [3:0] ext_bready_o,
 input [7:0] ext_bresp_i,
 input uart_rx_valid_i,
 input [7:0] uart_rx_data_i,
 output uart_rx_ready_o,
 output uart_tx_valid_o,
 output [7:0] uart_tx_data_o,
 input [31:0] external_irq_sources_i,
 output syscon_valid_o,
 output [31:0] syscon_value_o,
 output [63:0] time_o,
 output protocol_error_o
);
 wire arvalid;
 wire arready;
 wire [3:0] arid;
 wire [63:0] araddr;
 wire [7:0] arlen;
 wire [2:0] arsize;
 wire [2:0] arprot;
 wire [1:0] arburst;
 wire rvalid;
 wire rready;
 wire [3:0] rid;
 wire [63:0] rdata;
 wire [1:0] rresp;
 wire rlast;
 wire awvalid;
 wire awready;
 wire [3:0] awid;
 wire [63:0] awaddr;
 wire [7:0] awlen;
 wire [2:0] awsize;
 wire [2:0] awprot;
 wire [1:0] awburst;
 wire wvalid;
 wire wready;
 wire [63:0] wdata;
 wire [7:0] wstrb;
 wire wlast;
 wire bvalid;
 wire bready;
 wire [3:0] bid;
 wire [1:0] bresp;
 wire timer_wait;
 wire irq_software,irq_timer,irq_external,irq_supervisor_external,core_error,platform_error;
 assign protocol_error_o=core_error||platform_error;
 R64CoreTop core(
  .clk_i(clk_i),
  .rst_i(rst_i),
  .run_i(run_i),
  .time_i(time_o),
  .irq_software_i(irq_software),
  .irq_timer_i(irq_timer),
  .irq_external_i(irq_external),.irq_supervisor_external_i(irq_supervisor_external),
  .dma_invalidate_i(dma_invalidate_i),.wfi_wait_i(timer_wait),
  .arvalid_o(arvalid),
  .arready_i(arready),
  .arid_o(arid),
  .araddr_o(araddr),
  .arlen_o(arlen),
  .arsize_o(arsize),
  .arprot_o(arprot),
  .arburst_o(arburst),
  .rvalid_i(rvalid),
  .rready_o(rready),
  .rid_i(rid),
  .rdata_i(rdata),
  .rresp_i(rresp),
  .rlast_i(rlast),
  .awvalid_o(awvalid),
  .awready_i(awready),
  .awid_o(awid),
  .awaddr_o(awaddr),
  .awlen_o(awlen),
  .awsize_o(awsize),
  .awprot_o(awprot),
  .awburst_o(awburst),
  .wvalid_o(wvalid),
  .wready_i(wready),
  .wdata_o(wdata),
  .wstrb_o(wstrb),
  .wlast_o(wlast),
  .bvalid_i(bvalid),
  .bready_o(bready),
  .bid_i(bid),
  .bresp_i(bresp),
  .tensor_cmd_valid_o(tensor_cmd_valid_o),
  .tensor_cmd_ready_i(tensor_cmd_ready_i),
  .tensor_cmd_tag_o(tensor_cmd_tag_o),
  .tensor_cmd_o(tensor_cmd_o),
  .tensor_operand_o(tensor_operand_o),
  .tensor_pair_o(tensor_pair_o),
  .tensor_class_o(tensor_class_o),
  .tensor_terminal_valid_i(tensor_terminal_valid_i),
  .tensor_terminal_ready_o(tensor_terminal_ready_o),
  .tensor_terminal_tag_i(tensor_terminal_tag_i),
  .tensor_error_i(tensor_error_i),
  .tensor_error_code_i(tensor_error_code_i),
  .trace_ready_i(trace_ready_i),
  .trace_valid_o(trace_valid_o),
  .trace_pc_o(trace_pc_o),
  .trace_raw_o(trace_raw_o),
  .trace_npc_o(trace_npc_o),
  .trace_data_o(trace_data_o),
  .trace_length_o(trace_length_o),
  .trace_rd_write_o(trace_rd_write_o),
  .trace_rd_fp_o(trace_rd_fp_o),
  .trace_rd_arch_o(trace_rd_arch_o),
  .trace_fflags_o(trace_fflags_o),
  .trace_kind_o(trace_kind_o),
  .trap_valid_o(trap_valid_o),
  .trap_interrupt_o(trap_interrupt_o),
  .trap_cause_o(trap_cause_o),
  .trap_pc_o(trap_pc_o),
  .trap_tval_o(trap_tval_o),
  .trap_raw_o(trap_raw_o),
  .trap_target_o(trap_target_o),
  .trap_length_o(trap_length_o),
  .privilege_o(privilege_o),
  .mstatus_o(mstatus_o),
  .satp_o(satp_o),
  .rob_count_o(rob_count_o),
  .protocol_error_o(core_error)
 );
 R64AxiPlatform platform(
  .clk_i(clk_i),
  .rst_i(rst_i),
  .arvalid_i(arvalid),
  .arready_o(arready),
  .arid_i(arid),
  .araddr_i(araddr),
  .arlen_i(arlen),
  .arsize_i(arsize),
  .arprot_i(arprot),
  .arburst_i(arburst),
  .rvalid_o(rvalid),
  .rready_i(rready),
  .rid_o(rid),
  .rdata_o(rdata),
  .rresp_o(rresp),
  .rlast_o(rlast),
  .awvalid_i(awvalid),
  .awready_o(awready),
  .awid_i(awid),
  .awaddr_i(awaddr),
  .awlen_i(awlen),
  .awsize_i(awsize),
  .awburst_i(awburst),
  .wvalid_i(wvalid),
  .wready_o(wready),
  .wdata_i(wdata),
  .wstrb_i(wstrb),
  .wlast_i(wlast),
  .bvalid_o(bvalid),
  .bready_i(bready),
  .bid_o(bid),
  .bresp_o(bresp),
  .ext_arvalid_o(ext_arvalid_o),
  .ext_arready_i(ext_arready_i),
  .ext_araddr_o(ext_araddr_o),
  .ext_arsize_o(ext_arsize_o),
  .ext_arprot_o(ext_arprot_o),
  .ext_rvalid_i(ext_rvalid_i),
  .ext_rready_o(ext_rready_o),
  .ext_rdata_i(ext_rdata_i),
  .ext_rresp_i(ext_rresp_i),
  .ext_awvalid_o(ext_awvalid_o),
  .ext_awready_i(ext_awready_i),
  .ext_awaddr_o(ext_awaddr_o),
  .ext_awsize_o(ext_awsize_o),
  .ext_wvalid_o(ext_wvalid_o),
  .ext_wready_i(ext_wready_i),
  .ext_wdata_o(ext_wdata_o),
  .ext_wstrb_o(ext_wstrb_o),
  .ext_bvalid_i(ext_bvalid_i),
  .ext_bready_o(ext_bready_o),
  .ext_bresp_i(ext_bresp_i),
  .uart_rx_valid_i(uart_rx_valid_i),
  .uart_rx_data_i(uart_rx_data_i),
  .uart_rx_ready_o(uart_rx_ready_o),
  .uart_tx_valid_o(uart_tx_valid_o),
  .uart_tx_data_o(uart_tx_data_o),
  .external_irq_sources_i(external_irq_sources_i),
  .time_o(time_o),.timer_wait_o(timer_wait),
  .irq_software_o(irq_software),
  .irq_timer_o(irq_timer),
  .irq_external_o(irq_external),.irq_supervisor_external_o(irq_supervisor_external),
  .syscon_valid_o(syscon_valid_o),
  .syscon_value_o(syscon_value_o),
  .protocol_error_o(platform_error)
 );
endmodule
