# NPC RTL source catalog.
# 按功能目录集中维护 filelist，主仿真、模块 testbench 和综合入口共享同一份路径清单。

VSRCDIR ?= $(abspath ./vsrc)

RTL_INCLUDE_DIR := $(VSRCDIR)/include
RTL_COMMON_DIR := $(VSRCDIR)/common
RTL_CORE_DIR := $(VSRCDIR)/core
RTL_FRONTEND_DIR := $(VSRCDIR)/frontend
RTL_DECODE_DIR := $(VSRCDIR)/decode
RTL_EXECUTE_DIR := $(VSRCDIR)/execute
RTL_MEMORY_DIR := $(VSRCDIR)/memory
RTL_CACHE_DIR := $(VSRCDIR)/cache
RTL_BUS_DIR := $(VSRCDIR)/bus
RTL_PIPELINE_DIR := $(VSRCDIR)/pipeline
RTL_WRITEBACK_DIR := $(VSRCDIR)/writeback
RTL_SIM_DIR := $(VSRCDIR)/sim

RTL_DEFINE := $(RTL_INCLUDE_DIR)/define.v

RTL_SRAM1RW := $(RTL_COMMON_DIR)/Sram1Rw.v
RTL_SRAM2R1W := $(RTL_COMMON_DIR)/Sram2R1W.v

RTL_NPC_CORE := $(RTL_CORE_DIR)/NpcCore.v
RTL_REGISTER_FILE := $(RTL_CORE_DIR)/RegisterFile.v
RTL_CSR_FILE := $(RTL_CORE_DIR)/CsrFile.v
RTL_PIPELINE_CONTROL := $(RTL_CORE_DIR)/PipelineControl.v

RTL_IF_STAGE := $(RTL_FRONTEND_DIR)/IfStage.v
RTL_BRANCH_PREDICTOR := $(RTL_FRONTEND_DIR)/BranchPredictor.v

RTL_DECODE_STAGE := $(RTL_DECODE_DIR)/DecodeStage.v
RTL_DECODE_UNIT := $(RTL_DECODE_DIR)/DecodeUnit.v
RTL_IMM_GEN := $(RTL_DECODE_DIR)/ImmGen.v

RTL_ALU := $(RTL_EXECUTE_DIR)/ALU.v
RTL_COMPARE_UNIT := $(RTL_EXECUTE_DIR)/CompareUnit.v
RTL_RV32_MULTIPLIER := $(RTL_EXECUTE_DIR)/Rv32Multiplier.v
RTL_RV32_DIVIDER := $(RTL_EXECUTE_DIR)/Rv32Divider.v

RTL_LSU := $(RTL_MEMORY_DIR)/LSU.v
RTL_LSU_CONTROL := $(RTL_MEMORY_DIR)/LSUControl.v
RTL_LSU_DATAPATH := $(RTL_MEMORY_DIR)/LSUDataPath.v
RTL_MEMORY_STAGE := $(RTL_MEMORY_DIR)/MemoryStage.v
RTL_MEMORY_STAGE_CONTROL := $(RTL_MEMORY_DIR)/MemoryStageControl.v

RTL_CACHE_CONTROL := $(RTL_CACHE_DIR)/CacheControl.v
RTL_ICACHE := $(RTL_CACHE_DIR)/ICache.v
RTL_DCACHE := $(RTL_CACHE_DIR)/DCache.v

RTL_NPC_AXI_BUS := $(RTL_BUS_DIR)/NpcAxiBus.v
RTL_AXI_LITE_XBAR := $(RTL_BUS_DIR)/AxiLiteXbar.v
RTL_AXI_DEFAULT_SLAVE := $(RTL_BUS_DIR)/AxiDefaultSlave.v
RTL_AXI_LITE_CLINT := $(RTL_BUS_DIR)/AxiLiteClint.v
RTL_UART := $(RTL_BUS_DIR)/Uart.v
RTL_AXI_LITE_TO_UART := $(RTL_BUS_DIR)/AxiLiteToUart.v

RTL_IF_ID_PIPE_REG := $(RTL_PIPELINE_DIR)/IfIdPipeReg.v
RTL_ID_EX_PIPE_REG := $(RTL_PIPELINE_DIR)/IdExPipeReg.v
RTL_EX_MEM_PIPE_REG := $(RTL_PIPELINE_DIR)/ExMemPipeReg.v
RTL_MEM_WB_PIPE_REG := $(RTL_PIPELINE_DIR)/MemWbPipeReg.v

RTL_WBU := $(RTL_WRITEBACK_DIR)/WBU.v

RTL_AXI_DPI_SLAVE := $(RTL_SIM_DIR)/AxiDpiSlave.sv
RTL_NPC_SIM_TOP := $(RTL_SIM_DIR)/NpcSimTop.sv

RTL_HEADER_SRCS := $(RTL_DEFINE)
RTL_CORE_SRCS := $(strip \
	$(RTL_ALU) \
		$(RTL_AXI_DEFAULT_SLAVE) \
		$(RTL_AXI_LITE_CLINT) \
		$(RTL_AXI_LITE_XBAR) \
	$(RTL_UART) \
	$(RTL_AXI_LITE_TO_UART) \
	$(RTL_BRANCH_PREDICTOR) \
	$(RTL_CACHE_CONTROL) \
	$(RTL_COMPARE_UNIT) \
	$(RTL_CSR_FILE) \
	$(RTL_DCACHE) \
	$(RTL_DECODE_STAGE) \
	$(RTL_DECODE_UNIT) \
	$(RTL_ICACHE) \
	$(RTL_IF_STAGE) \
	$(RTL_IMM_GEN) \
	$(RTL_IF_ID_PIPE_REG) \
	$(RTL_ID_EX_PIPE_REG) \
	$(RTL_EX_MEM_PIPE_REG) \
	$(RTL_LSU_CONTROL) \
	$(RTL_LSU_DATAPATH) \
	$(RTL_LSU) \
	$(RTL_MEM_WB_PIPE_REG) \
	$(RTL_MEMORY_STAGE_CONTROL) \
	$(RTL_MEMORY_STAGE) \
	$(RTL_NPC_AXI_BUS) \
	$(RTL_PIPELINE_CONTROL) \
	$(RTL_REGISTER_FILE) \
	$(RTL_RV32_MULTIPLIER) \
	$(RTL_RV32_DIVIDER) \
	$(RTL_SRAM1RW) \
	$(RTL_SRAM2R1W) \
	$(RTL_WBU) \
	$(RTL_NPC_CORE))
SIM_TOP_SRCS := $(RTL_AXI_DPI_SLAVE) $(RTL_NPC_SIM_TOP)
VSRCS = $(RTL_CORE_SRCS) $(SIM_TOP_SRCS)
