`include "define.v"

// Direct custom-2 fetch owner.  This block only owns Tensor words which have
// already been normalized to 32-bit fetch slots.  It deliberately does not
// duplicate RVC length decoding or ordinary instruction decode.
//
// A command leaves this owner only on tensor_valid_o && tensor_ready_i.  Until
// that fire, command identity and payload remain resident here.  A cross-packet
// LO consumes no following word until the immediately adjacent HI is proven.
// On mismatch the LO is reported through the error channel while the current
// FIFO packet is left untouched for ordinary decode.
module OooTensorPairOwner (
  input clk,
  input rst,
  input flush_i,

  input head_valid_i,
  input head_slot1_valid_i,
  input [`XLEN-1:0] head_pc0_i,
  input [`INST_W-1:0] head_inst0_i,
  input [1:0] head_resp0_i,
  input [`XLEN-1:0] head_pc1_i,
  input [`INST_W-1:0] head_inst1_i,
  input [1:0] head_resp1_i,
  // Precise fetch-fault frontier carried with the normalized FIFO packet.
  // For a faulting HI word this is the architectural xtval, not the saved LO
  // instruction bits.
  input [`XLEN-1:0] head_fault_tval_i,

  // Existing frontend confirms that ordinary lane0 fired alone.  If lane1 is
  // a Tensor SINGLE/LO, this event transfers lane1 from the FIFO to this owner.
  input normal_lane0_fire_i,

  // Combinational claims used by the future frontend adapter.  head0 claim
  // blocks ordinary lane0 decode; lane1 claim forces an ordinary lane0-only
  // fire before Tensor lane1 capture.  head_pop_o is the only FIFO consume
  // event generated by this owner.
  output head0_claim_o,
  output head1_claim_o,
  output head_pop_o,

  // A post-command slot is retained explicitly.  It is never discarded when
  // a same/cross-packet pair consumes the enclosing packet.
  output residual_valid_o,
  input residual_ready_i,
  output [`XLEN-1:0] residual_pc_o,
  output [`INST_W-1:0] residual_inst_o,
  output [1:0] residual_resp_o,

  output tensor_valid_o,
  input tensor_ready_i,
  output [`XLEN-1:0] tensor_pc_o,
  output [`XLEN-1:0] tensor_next_pc_o,
  output [63:0] tensor_bits_o,
  output tensor_is_64_o,
  output tensor_required_o,
  output [7:0] tensor_opclass_o,
  output tensor_cross_packet_o,

  // Pair faults remain an integration sideband because the architectural
  // Tensor exception cause/tval ABI is not frozen yet.  No NPU command can
  // fire for an item resident in this channel.
  output error_valid_o,
  input error_ready_i,
  output [`XLEN-1:0] error_pc_o,
  output [`TRAP_CAUSE_W-1:0] error_cause_o,
  output [`XLEN-1:0] error_tval_o,
  output [1:0] error_code_o,

  output pair_pending_o,
  output serialize_o
);

  localparam [6:0] CUSTOM2_OPCODE = 7'b1011011;
  localparam [2:0] CONFIG_FUNCT3 = 3'b100;
  localparam [2:0] TENSOR_FUNCT3 = 3'b011;
  localparam [7:0] OPCLASS_CONTROL = 8'd0;
  localparam [7:0] OPCLASS_TIU = 8'd1;
  localparam [7:0] OPCLASS_GDMA = 8'd2;
  localparam [1:0] ERROR_MISMATCH = 2'd1;
  localparam [1:0] ERROR_FETCH = 2'd2;

  localparam [1:0] PAIR_IDLE = 2'd0;
  localparam [1:0] PAIR_WAIT_HI = 2'd1;

  reg [1:0] pair_state_q;
  reg [`XLEN-1:0] lo_pc_q;
  reg [`INST_W-1:0] lo_inst_q;
  reg lo_cross_packet_q;

  reg tensor_valid_q;
  reg [`XLEN-1:0] tensor_pc_q;
  reg [`XLEN-1:0] tensor_next_pc_q;
  reg [63:0] tensor_bits_q;
  reg tensor_is_64_q;
  reg tensor_required_q;
  reg [7:0] tensor_opclass_q;
  reg tensor_cross_packet_q;

  reg residual_valid_q;
  reg [`XLEN-1:0] residual_pc_q;
  reg [`INST_W-1:0] residual_inst_q;
  reg [1:0] residual_resp_q;

  reg error_valid_q;
  reg [`XLEN-1:0] error_pc_q;
  reg [`TRAP_CAUSE_W-1:0] error_cause_q;
  reg [`XLEN-1:0] error_tval_q;
  reg [1:0] error_code_q;

  wire tensor_empty_w = !tensor_valid_q;
  wire residual_empty_w = !residual_valid_q;
  wire error_empty_w = !error_valid_q;
  wire owner_buffers_empty_w = tensor_empty_w && residual_empty_w && error_empty_w;

  wire slot0_ok_w = head_valid_i && (head_resp0_i == 2'b00);
  wire slot1_ok_w = head_valid_i && head_slot1_valid_i &&
                    (head_resp1_i == 2'b00);

  wire slot0_single_w = slot0_ok_w &&
      (head_inst0_i[6:0] == CUSTOM2_OPCODE) &&
      (head_inst0_i[14:12] == CONFIG_FUNCT3);
  wire slot1_single_w = slot1_ok_w &&
      (head_inst1_i[6:0] == CUSTOM2_OPCODE) &&
      (head_inst1_i[14:12] == CONFIG_FUNCT3);
  wire slot0_lo_w = slot0_ok_w &&
      (head_inst0_i[6:0] == CUSTOM2_OPCODE) &&
      (head_inst0_i[14:12] == TENSOR_FUNCT3) &&
      (head_inst0_i[31:27] == 5'b00000) && head_inst0_i[25];
  wire slot1_lo_w = slot1_ok_w &&
      (head_inst1_i[6:0] == CUSTOM2_OPCODE) &&
      (head_inst1_i[14:12] == TENSOR_FUNCT3) &&
      (head_inst1_i[31:27] == 5'b00000) && head_inst1_i[25];
  wire slot0_hi_tiu_w = slot0_ok_w &&
      (head_inst0_i[6:0] == CUSTOM2_OPCODE) &&
      (head_inst0_i[14:12] == TENSOR_FUNCT3) &&
      (head_inst0_i[31:25] == 7'b0000101);
  wire slot0_hi_gdma_w = slot0_ok_w &&
      (head_inst0_i[6:0] == CUSTOM2_OPCODE) &&
      (head_inst0_i[14:12] == TENSOR_FUNCT3) &&
      (head_inst0_i[31:25] == 7'b0000111);
  wire slot0_hi_w = slot0_hi_tiu_w || slot0_hi_gdma_w;
  wire slot1_hi_tiu_w = slot1_ok_w &&
      (head_inst1_i[6:0] == CUSTOM2_OPCODE) &&
      (head_inst1_i[14:12] == TENSOR_FUNCT3) &&
      (head_inst1_i[31:25] == 7'b0000101);
  wire slot1_hi_gdma_w = slot1_ok_w &&
      (head_inst1_i[6:0] == CUSTOM2_OPCODE) &&
      (head_inst1_i[14:12] == TENSOR_FUNCT3) &&
      (head_inst1_i[31:25] == 7'b0000111);
  wire slot1_hi_w = slot1_hi_tiu_w || slot1_hi_gdma_w;

  wire idle_owner_w = (pair_state_q == PAIR_IDLE) && owner_buffers_empty_w;
  wire wait_owner_w = (pair_state_q == PAIR_WAIT_HI) && owner_buffers_empty_w;
  wire adjacent0_w = (head_pc0_i == (lo_pc_q + {{(`XLEN-3){1'b0}}, 3'd4}));

  wire take_single0_w = idle_owner_w && slot0_single_w;
  wire take_lo0_same_pair_w = idle_owner_w && slot0_lo_w &&
                              head_slot1_valid_i && slot1_hi_w &&
                              (head_pc1_i == (head_pc0_i + {{(`XLEN-3){1'b0}}, 3'd4}));
  wire take_lo0_same_fault_w = idle_owner_w && slot0_lo_w &&
                               head_slot1_valid_i && (head_resp1_i != 2'b00) &&
                               (head_pc1_i == (head_pc0_i + {{(`XLEN-3){1'b0}}, 3'd4}));
  wire take_lo0_same_mismatch_w = idle_owner_w && slot0_lo_w &&
                                  head_slot1_valid_i &&
                                  !take_lo0_same_pair_w && !take_lo0_same_fault_w;
  wire take_lo0_wait_w = idle_owner_w && slot0_lo_w && !head_slot1_valid_i;
  wire take_lane1_single_w = idle_owner_w && normal_lane0_fire_i &&
                             !slot0_single_w && !slot0_lo_w && slot1_single_w;
  wire take_lane1_lo_w = idle_owner_w && normal_lane0_fire_i &&
                         !slot0_single_w && !slot0_lo_w && slot1_lo_w;

  wire wait_take_pair_w = wait_owner_w && head_valid_i && adjacent0_w && slot0_hi_w;
  wire wait_take_fault_w = wait_owner_w && head_valid_i && adjacent0_w &&
                           (head_resp0_i != 2'b00);
  wire wait_mismatch_w = wait_owner_w && head_valid_i &&
                         !wait_take_pair_w && !wait_take_fault_w;

  assign head0_claim_o = owner_buffers_empty_w &&
      (((pair_state_q == PAIR_IDLE) && (slot0_single_w || slot0_lo_w)) ||
       (pair_state_q == PAIR_WAIT_HI));
  assign head1_claim_o = idle_owner_w && !slot0_single_w && !slot0_lo_w &&
                         (slot1_single_w || slot1_lo_w);
  assign head_pop_o = take_single0_w || take_lo0_same_pair_w ||
                      take_lo0_same_fault_w || take_lo0_same_mismatch_w ||
                      take_lo0_wait_w || take_lane1_single_w ||
                      take_lane1_lo_w || wait_take_pair_w || wait_take_fault_w;

  assign residual_valid_o = residual_valid_q;
  assign residual_pc_o = residual_pc_q;
  assign residual_inst_o = residual_inst_q;
  assign residual_resp_o = residual_resp_q;

  assign tensor_valid_o = tensor_valid_q;
  assign tensor_pc_o = tensor_pc_q;
  assign tensor_next_pc_o = tensor_next_pc_q;
  assign tensor_bits_o = tensor_bits_q;
  assign tensor_is_64_o = tensor_is_64_q;
  assign tensor_required_o = tensor_required_q;
  assign tensor_opclass_o = tensor_opclass_q;
  assign tensor_cross_packet_o = tensor_cross_packet_q;

  assign error_valid_o = error_valid_q;
  assign error_pc_o = error_pc_q;
  assign error_cause_o = error_cause_q;
  assign error_tval_o = error_tval_q;
  assign error_code_o = error_code_q;

  assign pair_pending_o = (pair_state_q == PAIR_WAIT_HI);
  assign serialize_o = (pair_state_q != PAIR_IDLE) || tensor_valid_q ||
                       error_valid_q;

  always @(posedge clk) begin
    if (rst) begin
      pair_state_q <= PAIR_IDLE;
      lo_pc_q <= {`XLEN{1'b0}};
      lo_inst_q <= {`INST_W{1'b0}};
      lo_cross_packet_q <= 1'b0;
      tensor_valid_q <= 1'b0;
      tensor_pc_q <= {`XLEN{1'b0}};
      tensor_next_pc_q <= {`XLEN{1'b0}};
      tensor_bits_q <= 64'b0;
      tensor_is_64_q <= 1'b0;
      tensor_required_q <= 1'b0;
      tensor_opclass_q <= OPCLASS_CONTROL;
      tensor_cross_packet_q <= 1'b0;
      residual_valid_q <= 1'b0;
      residual_pc_q <= {`XLEN{1'b0}};
      residual_inst_q <= {`INST_W{1'b0}};
      residual_resp_q <= 2'b00;
      error_valid_q <= 1'b0;
      error_pc_q <= {`XLEN{1'b0}};
      error_cause_q <= {`TRAP_CAUSE_W{1'b0}};
      error_tval_q <= {`XLEN{1'b0}};
      error_code_q <= 2'b00;
    end else if (flush_i) begin
      pair_state_q <= PAIR_IDLE;
      tensor_valid_q <= 1'b0;
      residual_valid_q <= 1'b0;
      error_valid_q <= 1'b0;
    end else begin
      if (tensor_valid_q && tensor_ready_i)
        tensor_valid_q <= 1'b0;
      if (residual_valid_q && residual_ready_i)
        residual_valid_q <= 1'b0;
      if (error_valid_q && error_ready_i) begin
        error_valid_q <= 1'b0;
        // A same-packet mismatch may have retained slot1 as a residual.  It is
        // younger than the faulting LO and must be refetched after the trap;
        // transferring the trap owner therefore releases the residual shadow
        // atomically as well.
        residual_valid_q <= 1'b0;
      end

      if (take_single0_w || take_lane1_single_w) begin
        pair_state_q <= PAIR_IDLE;
        tensor_valid_q <= 1'b1;
        tensor_pc_q <= take_single0_w ? head_pc0_i : head_pc1_i;
        tensor_next_pc_q <= (take_single0_w ? head_pc0_i : head_pc1_i) +
                            {{(`XLEN-3){1'b0}}, 3'd4};
        tensor_bits_q <= {32'b0, take_single0_w ? head_inst0_i : head_inst1_i};
        tensor_is_64_q <= 1'b0;
        tensor_required_q <= 1'b0;
        tensor_opclass_q <= OPCLASS_CONTROL;
        tensor_cross_packet_q <= 1'b0;
        if (take_single0_w && head_slot1_valid_i) begin
          residual_valid_q <= 1'b1;
          residual_pc_q <= head_pc1_i;
          residual_inst_q <= head_inst1_i;
          residual_resp_q <= head_resp1_i;
        end
      end else if (take_lo0_same_pair_w) begin
        pair_state_q <= PAIR_IDLE;
        tensor_valid_q <= 1'b1;
        tensor_pc_q <= head_pc0_i;
        tensor_next_pc_q <= head_pc0_i + {{(`XLEN-4){1'b0}}, 4'd8};
        tensor_bits_q <= {head_inst1_i, head_inst0_i};
        tensor_is_64_q <= 1'b1;
        tensor_required_q <= 1'b1;
        tensor_opclass_q <= slot1_hi_gdma_w ? OPCLASS_GDMA : OPCLASS_TIU;
        tensor_cross_packet_q <= 1'b0;
      end else if (take_lo0_same_fault_w || take_lo0_same_mismatch_w) begin
        pair_state_q <= PAIR_IDLE;
        error_valid_q <= 1'b1;
        error_pc_q <= head_pc0_i;
        error_cause_q <= take_lo0_same_fault_w ?
            ((head_resp1_i == 2'b10) ? `EXC_INST_PAGE_FAULT :
                                       `EXC_INST_ACCESS_FAULT) :
            `EXC_ILLEGAL_INST;
        error_tval_q <= take_lo0_same_fault_w ? head_fault_tval_i :
            {{(`XLEN-`INST_W){1'b0}}, head_inst0_i};
        error_code_q <= take_lo0_same_fault_w ? ERROR_FETCH : ERROR_MISMATCH;
        if (take_lo0_same_mismatch_w) begin
          residual_valid_q <= 1'b1;
          residual_pc_q <= head_pc1_i;
          residual_inst_q <= head_inst1_i;
          residual_resp_q <= head_resp1_i;
        end
      end else if (take_lo0_wait_w || take_lane1_lo_w) begin
        pair_state_q <= PAIR_WAIT_HI;
        lo_pc_q <= take_lo0_wait_w ? head_pc0_i : head_pc1_i;
        lo_inst_q <= take_lo0_wait_w ? head_inst0_i : head_inst1_i;
        lo_cross_packet_q <= 1'b1;
      end else if (wait_take_pair_w) begin
        pair_state_q <= PAIR_IDLE;
        tensor_valid_q <= 1'b1;
        tensor_pc_q <= lo_pc_q;
        tensor_next_pc_q <= lo_pc_q + {{(`XLEN-4){1'b0}}, 4'd8};
        tensor_bits_q <= {head_inst0_i, lo_inst_q};
        tensor_is_64_q <= 1'b1;
        tensor_required_q <= 1'b1;
        tensor_opclass_q <= slot0_hi_gdma_w ? OPCLASS_GDMA : OPCLASS_TIU;
        tensor_cross_packet_q <= lo_cross_packet_q;
        if (head_slot1_valid_i) begin
          residual_valid_q <= 1'b1;
          residual_pc_q <= head_pc1_i;
          residual_inst_q <= head_inst1_i;
          residual_resp_q <= head_resp1_i;
        end
      end else if (wait_take_fault_w) begin
        pair_state_q <= PAIR_IDLE;
        error_valid_q <= 1'b1;
        error_pc_q <= lo_pc_q;
        error_cause_q <= (head_resp0_i == 2'b10) ?
            `EXC_INST_PAGE_FAULT : `EXC_INST_ACCESS_FAULT;
        error_tval_q <= head_fault_tval_i;
        error_code_q <= ERROR_FETCH;
      end else if (wait_mismatch_w) begin
        // Do not pop the current packet.  It becomes ordinary decode input
        // after the LO error is accepted.
        pair_state_q <= PAIR_IDLE;
        error_valid_q <= 1'b1;
        error_pc_q <= lo_pc_q;
        error_cause_q <= `EXC_ILLEGAL_INST;
        error_tval_q <= {{(`XLEN-`INST_W){1'b0}}, lo_inst_q};
        error_code_q <= ERROR_MISMATCH;
      end
    end
  end

endmodule
