`include "R64Uop.vh"
// Native 2-wide backend: one birth allocates ROB, rename, IQ and MEM LSQ owner.
// Only canonical ROB-accepted completion tuples write/wake the PRF. All
// external effects belong to tagged LSU/FP/serial owners beyond their ingress.
module R64BackendCommitActual #(parameter TAG_W=9,parameter ROB_W=5,parameter PREDECODED=1,parameter PREPARED_NPC=1,parameter PRECONTROLLED=1,parameter LSQ_W=5)(
  input clk,input rst,input flush_i,input stop_i,
  input irq_pending_i,input [5:0] irq_cause_i,input [63:0] trap_target_i,
  input lsu_irrevocable_i,serial_irrevocable_i,
  output control_full_flush_o,control_stop_o,control_redirect_o,
  output [63:0] control_target_o,output [1:0] retire_fire_o,retired_count_o,
  output [127:0] retire_npc_o,output fp_dirty_o,output [4:0] fp_flags_o,
  output serial_commit_o,output [8:0] serial_commit_tag_o,
  output trap_o,trap_interrupt_o,output [5:0] trap_cause_o,
  output [63:0] trap_pc_o,trap_tval_o,output effect_allow_o,serial_issue_allow_o,trap_prepare_o,

  input [(1<<ROB_W)-1:0] reuse_block_i,
  input [1:0] fetch_valid_i,output [1:0] fetch_ready_o,
  input [65:0] fetch_canonical_i,input [69:0] fetch_control_i,input [127:0] fetch_sequential_npc_i,
  input [127:0] fetch_pc_i,fetch_raw_i,fetch_pred_npc_i,
  input [7:0] fetch_length_i,
  input [1:0] fetch_exception_i,input [11:0] fetch_cause_i,input [127:0] fetch_tval_i,
  input [1:0] commit_ready_i,
  output [1:0] commit_valid_o,output [2*TAG_W-1:0] commit_tag_o,
  output [2*`R64_META_W-1:0] commit_meta_o,
  output [127:0] commit_data_o,output [1:0] commit_exception_o,
  output [11:0] commit_cause_o,output [127:0] commit_tval_o,output [9:0] commit_fflags_o,
  output [1:0] commit_rd_write_o,commit_rd_fp_o,output [9:0] commit_rd_arch_o,
  output redirect_valid_o,output [63:0] redirect_pc_o,
  output resolve_valid_o,output [TAG_W-1:0] resolve_tag_o,
  output [63:0] resolve_pc_o,resolve_npc_o,
  output resolve_conditional_o,resolve_indirect_o,resolve_taken_o,
  output [(1<<ROB_W)-1:0] kill_mask_o,
  output [TAG_W-1:0] head_tag_o,output [ROB_W:0] rob_count_o,output recover_o,
  // LSQ ownership is allocated atomically with ROB/rename/IQ birth.
  output [1:0] lsu_reserve_want_o,output [1:0] lsu_reserve_fire_o,
  output [2*TAG_W-1:0] lsu_reserve_tag_o,
  output [15:0] lsu_reserve_func_o,output [9:0] lsu_reserve_amo_o,
  input [1:0] lsu_reserve_ready_i,input [2*LSQ_W-1:0] lsu_reserve_slot_i,
  input [1:0] lsu_ready_i,output [1:0] lsu_fire_o,
  output [2*TAG_W-1:0] lsu_tag_o,output [2*`R64_UOP_W-1:0] lsu_uop_o,
  output [383:0] lsu_operand_o,output [2*LSQ_W-1:0] lsu_slot_o,
  input fp_ready_i,output fp_fire_o,output [TAG_W-1:0] fp_tag_o,
  output [`R64_UOP_W-1:0] fp_uop_o,output [191:0] fp_operand_o,
  input serial_ready_i,output serial_fire_o,output [TAG_W-1:0] serial_tag_o,
  output [`R64_UOP_W-1:0] serial_uop_o,output [191:0] serial_operand_o,
  // Result lanes: LSU0, LSU1, FP, serial. VALID/payload remain stable until
  // READY, except an explicit kill/flush cancellation by the external owner.
  // Narrow precise terminal for the irrevocable ordinary store at ROB head.
  input store_done_valid_i,output store_done_ready_o,
  input [TAG_W-1:0] store_done_tag_i,input store_done_error_i,input [63:0] store_done_tval_i,
  input [3:0] external_valid_i,output [3:0] external_ready_o,
  input [4*TAG_W-1:0] external_tag_i,
  input [4*`R64_RESULT_W-1:0] external_result_i
);
 wire [1:0] serial_class_w;wire [1:0] retire_ready_w;wire second_allow_w;wire head_serial_w;wire head_exception_w;
 R64Backend #(.TAG_W(TAG_W),.ROB_W(ROB_W),.LSQ_W(LSQ_W),.PREDECODED(1),.PREPARED_NPC(1),.PRECONTROLLED(1)) dut(
  .clk(clk),
  .rst(rst),
  .flush_i(flush_i|control_full_flush_o),
  .stop_i(stop_i|control_stop_o),
  .serial_allow_i(serial_issue_allow_o),
  .reuse_block_i(reuse_block_i),
  .fetch_valid_i(fetch_valid_i),
  .fetch_ready_o(fetch_ready_o),
  .fetch_canonical_i(fetch_canonical_i),
  .fetch_control_i(fetch_control_i),
  .fetch_sequential_npc_i(fetch_sequential_npc_i),
  .fetch_pc_i(fetch_pc_i),
  .fetch_raw_i(fetch_raw_i),
  .fetch_pred_npc_i(fetch_pred_npc_i),
  .fetch_length_i(fetch_length_i),
  .fetch_exception_i(fetch_exception_i),
  .fetch_cause_i(fetch_cause_i),
  .fetch_tval_i(fetch_tval_i),
  .commit_ready_i(retire_ready_w),
  .commit1_allow_i(second_allow_w),
  .commit_valid_o(commit_valid_o),.commit_serial_o(serial_class_w),
  .commit_tag_o(commit_tag_o),
  .commit_meta_o(commit_meta_o),
  .commit_data_o(commit_data_o),
  .commit_exception_o(commit_exception_o),
  .commit_cause_o(commit_cause_o),
  .commit_tval_o(commit_tval_o),
  .commit_fflags_o(commit_fflags_o),
  .commit_rd_write_o(commit_rd_write_o),
  .commit_rd_fp_o(commit_rd_fp_o),
  .commit_rd_arch_o(commit_rd_arch_o),
  .redirect_valid_o(redirect_valid_o),
  .redirect_pc_o(redirect_pc_o),
  .resolve_valid_o(resolve_valid_o),
  .resolve_tag_o(resolve_tag_o),
  .resolve_pc_o(resolve_pc_o),
  .resolve_npc_o(resolve_npc_o),
  .resolve_conditional_o(resolve_conditional_o),
  .resolve_indirect_o(resolve_indirect_o),
  .resolve_taken_o(resolve_taken_o),
  .kill_mask_o(kill_mask_o),
  .head_tag_o(head_tag_o),.head_serial_o(head_serial_w),.head_exception_o(head_exception_w),
  .rob_count_o(rob_count_o),
  .recover_o(recover_o),
  .lsu_reserve_want_o(lsu_reserve_want_o),
  .lsu_reserve_fire_o(lsu_reserve_fire_o),
  .lsu_reserve_tag_o(lsu_reserve_tag_o),
  .lsu_reserve_func_o(lsu_reserve_func_o),
  .lsu_reserve_amo_o(lsu_reserve_amo_o),
  .lsu_reserve_ready_i(lsu_reserve_ready_i),
  .lsu_reserve_slot_i(lsu_reserve_slot_i),
  .lsu_ready_i(lsu_ready_i),
  .lsu_fire_o(lsu_fire_o),
  .lsu_tag_o(lsu_tag_o),
  .lsu_uop_o(lsu_uop_o),
  .lsu_operand_o(lsu_operand_o),
  .lsu_slot_o(lsu_slot_o),
  .fp_ready_i(fp_ready_i),
  .fp_fire_o(fp_fire_o),
  .fp_tag_o(fp_tag_o),
  .fp_uop_o(fp_uop_o),
  .fp_operand_o(fp_operand_o),
  .serial_ready_i(serial_ready_i),
  .serial_fire_o(serial_fire_o),
  .serial_tag_o(serial_tag_o),
  .serial_uop_o(serial_uop_o),
  .serial_operand_o(serial_operand_o),
  .store_done_valid_i(store_done_valid_i),
  .store_done_ready_o(store_done_ready_o),
  .store_done_tag_i(store_done_tag_i),
  .store_done_error_i(store_done_error_i),
  .store_done_tval_i(store_done_tval_i),
  .external_valid_i(external_valid_i),
  .external_ready_o(external_ready_o),
  .external_tag_i(external_tag_i),
  .external_result_i(external_result_i));

 R64Commit #(.HEAD_SERIAL_ISSUE(1),.HEAD_SERIAL_STOP(1),.HEAD_EXCEPTION_STOP(1),.HEAD_SERIAL_CLASS(1)) commit(
  .clk_i(clk),.rst_i(rst),.rob_valid_i(commit_valid_o),.rob_serial_i(serial_class_w),.rob_ready_o(retire_ready_w),.commit1_allow_o(second_allow_w),
  .rob_tag_i(commit_tag_o),.rob_meta_i(commit_meta_o),.rob_data_i(commit_data_o),
  .rob_exception_i(commit_exception_o),.rob_cause_i(commit_cause_o),.rob_tval_i(commit_tval_o),
  .rob_rd_write_i(commit_rd_write_o),.rob_rd_fp_i(commit_rd_fp_o),.rob_fflags_i(commit_fflags_o),
  .retire_ready_i(commit_ready_i),.rob_empty_i(rob_count_o==0),.head_serial_i(head_serial_w),.head_exception_i(head_exception_w),.recover_i(recover_o),
  .lsu_irrevocable_i(lsu_irrevocable_i),.serial_irrevocable_i(serial_irrevocable_i),
  .irq_pending_i(irq_pending_i),.irq_cause_i(irq_cause_i),.trap_target_i(trap_target_i),
  .retire_fire_o(retire_fire_o),.retire_npc_o(retire_npc_o),.retired_count_o(retired_count_o),
  .fp_dirty_o(fp_dirty_o),.fp_flags_o(fp_flags_o),.serial_commit_o(serial_commit_o),.serial_tag_o(serial_commit_tag_o),
  .trap_o(trap_o),.trap_interrupt_o(trap_interrupt_o),.trap_cause_o(trap_cause_o),
  .trap_pc_o(trap_pc_o),.trap_tval_o(trap_tval_o),
  .stop_birth_o(control_stop_o),.full_flush_o(control_full_flush_o),.redirect_o(control_redirect_o),
  .redirect_target_o(control_target_o),.effect_allow_o(effect_allow_o),
  .serial_allow_o(serial_issue_allow_o),.trap_prepare_o(trap_prepare_o));
`ifdef R64_ASSERT
 always @(posedge clk)if(serial_fire_o&&!effect_allow_o)
   $fatal(1,"Closed Serial fire violated original Commit permission");
`endif
endmodule

