#ifndef __RISCV64_INSTRUCTION_H__
#define __RISCV64_INSTRUCTION_H__

#include <common.h>
#include "privileged.h"

/*
 * 一条指令在 NEMU 中只经历一次体系结构译码。
 *
 * RvInstructionClass 对应非特权规范中的指令大类，只用于选择执行章节；
 * RvOperation 对应手册中的具体 mnemonic。execute 层不得重新解释 opcode、
 * funct3 或 funct7。原始编码只保留给异常 tval、日志以及尚未迁移的扩展适配器。
 */
typedef enum {
  RV_INSTRUCTION_CLASS_ILLEGAL = 0,
  RV_INSTRUCTION_CLASS_COMPRESSED,
  RV_INSTRUCTION_CLASS_INTEGER_IMMEDIATE,
  RV_INSTRUCTION_CLASS_INTEGER_IMMEDIATE_WORD,
  RV_INSTRUCTION_CLASS_INTEGER_REGISTER,
  RV_INSTRUCTION_CLASS_INTEGER_REGISTER_WORD,
  RV_INSTRUCTION_CLASS_LOAD,
  RV_INSTRUCTION_CLASS_STORE,
  RV_INSTRUCTION_CLASS_BRANCH,
  RV_INSTRUCTION_CLASS_JUMP,
  RV_INSTRUCTION_CLASS_UPPER_IMMEDIATE,
  RV_INSTRUCTION_CLASS_MEMORY_ORDERING,
  RV_INSTRUCTION_CLASS_SYSTEM,
  RV_INSTRUCTION_CLASS_FLOATING_POINT,
  RV_INSTRUCTION_CLASS_ATOMIC,
  RV_INSTRUCTION_CLASS_EXTENSION_ADAPTER,
  RV_INSTRUCTION_CLASS_COUNT,
} RvInstructionClass;

typedef enum {
  RV_OPERATION_ILLEGAL_INSTRUCTION = 0,

  /* RV64I integer computational instructions. */
  RV_OPERATION_ADDI,
  RV_OPERATION_SLTI,
  RV_OPERATION_SLTIU,
  RV_OPERATION_XORI,
  RV_OPERATION_ORI,
  RV_OPERATION_ANDI,
  RV_OPERATION_SLLI,
  RV_OPERATION_SRLI,
  RV_OPERATION_SRAI,
  RV_OPERATION_ADDIW,
  RV_OPERATION_SLLIW,
  RV_OPERATION_SRLIW,
  RV_OPERATION_SRAIW,
  RV_OPERATION_ADD,
  RV_OPERATION_SUB,
  RV_OPERATION_SLL,
  RV_OPERATION_SLT,
  RV_OPERATION_SLTU,
  RV_OPERATION_XOR,
  RV_OPERATION_SRL,
  RV_OPERATION_SRA,
  RV_OPERATION_OR,
  RV_OPERATION_AND,
  RV_OPERATION_ADDW,
  RV_OPERATION_SUBW,
  RV_OPERATION_SLLW,
  RV_OPERATION_SRLW,
  RV_OPERATION_SRAW,

  /* RV64I loads and stores. */
  RV_OPERATION_LB,
  RV_OPERATION_LH,
  RV_OPERATION_LW,
  RV_OPERATION_LD,
  RV_OPERATION_LBU,
  RV_OPERATION_LHU,
  RV_OPERATION_LWU,
  RV_OPERATION_SB,
  RV_OPERATION_SH,
  RV_OPERATION_SW,
  RV_OPERATION_SD,

  /* RV64I control transfer and upper-immediate instructions. */
  RV_OPERATION_BEQ,
  RV_OPERATION_BNE,
  RV_OPERATION_BLT,
  RV_OPERATION_BGE,
  RV_OPERATION_BLTU,
  RV_OPERATION_BGEU,
  RV_OPERATION_JAL,
  RV_OPERATION_JALR,
  RV_OPERATION_LUI,
  RV_OPERATION_AUIPC,

  /* Memory ordering and privileged/system instructions. */
  RV_OPERATION_FENCE,
  RV_OPERATION_FENCE_I,
  RV_OPERATION_ECALL,
  RV_OPERATION_EBREAK,
  RV_OPERATION_SRET,
  RV_OPERATION_MRET,
  RV_OPERATION_WFI,
  RV_OPERATION_SFENCE_VMA,
  RV_OPERATION_CSRRW,
  RV_OPERATION_CSRRS,
  RV_OPERATION_CSRRC,
  RV_OPERATION_CSRRWI,
  RV_OPERATION_CSRRSI,
  RV_OPERATION_CSRRCI,

  /* RV64C compressed instructions, named exactly as in the ISA manual. */
  RV_OPERATION_C_ADDI4SPN,
  RV_OPERATION_C_FLD,
  RV_OPERATION_C_LW,
  RV_OPERATION_C_LD,
  RV_OPERATION_C_FSD,
  RV_OPERATION_C_SW,
  RV_OPERATION_C_SD,
  RV_OPERATION_C_ADDI,
  RV_OPERATION_C_ADDIW,
  RV_OPERATION_C_LI,
  RV_OPERATION_C_ADDI16SP,
  RV_OPERATION_C_LUI,
  RV_OPERATION_C_SRLI,
  RV_OPERATION_C_SRAI,
  RV_OPERATION_C_ANDI,
  RV_OPERATION_C_SUB,
  RV_OPERATION_C_XOR,
  RV_OPERATION_C_OR,
  RV_OPERATION_C_AND,
  RV_OPERATION_C_SUBW,
  RV_OPERATION_C_ADDW,
  RV_OPERATION_C_J,
  RV_OPERATION_C_BEQZ,
  RV_OPERATION_C_BNEZ,
  RV_OPERATION_C_SLLI,
  RV_OPERATION_C_FLDSP,
  RV_OPERATION_C_LWSP,
  RV_OPERATION_C_LDSP,
  RV_OPERATION_C_JR,
  RV_OPERATION_C_MV,
  RV_OPERATION_C_EBREAK,
  RV_OPERATION_C_JALR,
  RV_OPERATION_C_ADD,
  RV_OPERATION_C_FSDSP,
  RV_OPERATION_C_SWSP,
  RV_OPERATION_C_SDSP,
  RV_OPERATION_C_HINT,

  /*
   * These adapters mark extensions whose internal decoder has not yet been
   * split from its executor. They are explicit migration boundaries, not a
   * second top-level interpreter and never live in decode_cache.c.
   */
  RV_OPERATION_BITMANIP_IMMEDIATE_ADAPTER,
  RV_OPERATION_BITMANIP_IMMEDIATE_WORD_ADAPTER,
  RV_OPERATION_M_EXTENSION_ADAPTER,
  RV_OPERATION_M_EXTENSION_WORD_ADAPTER,
  RV_OPERATION_BITMANIP_REGISTER_ADAPTER,
  RV_OPERATION_BITMANIP_REGISTER_WORD_ADAPTER,
  RV_OPERATION_FLOATING_LOAD_ADAPTER,
  RV_OPERATION_FLOATING_STORE_ADAPTER,
  RV_OPERATION_FMADD_ADAPTER,
  RV_OPERATION_FMSUB_ADAPTER,
  RV_OPERATION_FNMSUB_ADAPTER,
  RV_OPERATION_FNMADD_ADAPTER,
  RV_OPERATION_FLOATING_OPERATION_ADAPTER,
  RV_OPERATION_ATOMIC_ADAPTER,

  RV_OPERATION_COUNT,
} RvOperation;

typedef struct {
  uint32_t encoding;
  word_t immediate;
  RvInstructionClass instruction_class;
  RvOperation operation;
  RiscvCsrInstruction csr;
  uint8_t length;
  uint8_t rd;
  uint8_t rs1;
  uint8_t rs2;
  uint8_t rs3;
  uint8_t funct3;
  uint8_t funct7;
} RvDecodedInstruction;

static inline bool rv_decode_cache_lookup(vaddr_t pc, uint32_t encoding,
                                          RvDecodedInstruction *instruction);
static inline void rv_decode_cache_insert(
    vaddr_t pc, const RvDecodedInstruction *instruction);
static inline void rv_decode_cache_flush(void);

#endif
