#ifndef __RISCV64_INSTRUCTION_H__
#define __RISCV64_INSTRUCTION_H__

#include <common.h>
#include <isa/riscv/atomic.h>
#include <isa/riscv/compressed.h>
#include <isa/riscv/floating.h>
#include "privileged.h"

/*
 * 一条指令在 NEMU 中只经历一次体系结构译码。
 *
 * RvInstructionClass 对应非特权规范中的指令大类，只用于选择执行章节；
 * RvOperation 对应手册中的具体 mnemonic。execute 层不得重新解释 opcode、
 * funct3 或 funct7。原始编码只保留为 decode-cache key 与非法指令 tval；
 * 包括 M 与 Zba/Zbb/Zbc/Zbs 在内的所有实现均缓存完整语义描述符。
 */
typedef enum {
  RV_INSTRUCTION_CLASS_ILLEGAL = 0,
  RV_INSTRUCTION_CLASS_COMPRESSED,
  RV_INSTRUCTION_CLASS_INTEGER_IMMEDIATE,
  RV_INSTRUCTION_CLASS_INTEGER_IMMEDIATE_WORD,
  RV_INSTRUCTION_CLASS_INTEGER_REGISTER,
  RV_INSTRUCTION_CLASS_INTEGER_REGISTER_WORD,
  RV_INSTRUCTION_CLASS_MULTIPLY_DIVIDE,
  RV_INSTRUCTION_CLASS_MULTIPLY_DIVIDE_WORD,
  RV_INSTRUCTION_CLASS_BIT_MANIPULATION_IMMEDIATE,
  RV_INSTRUCTION_CLASS_BIT_MANIPULATION_IMMEDIATE_WORD,
  RV_INSTRUCTION_CLASS_BIT_MANIPULATION_REGISTER,
  RV_INSTRUCTION_CLASS_BIT_MANIPULATION_REGISTER_WORD,
  RV_INSTRUCTION_CLASS_LOAD,
  RV_INSTRUCTION_CLASS_STORE,
  RV_INSTRUCTION_CLASS_BRANCH,
  RV_INSTRUCTION_CLASS_JUMP,
  RV_INSTRUCTION_CLASS_UPPER_IMMEDIATE,
  RV_INSTRUCTION_CLASS_MEMORY_ORDERING,
  RV_INSTRUCTION_CLASS_SYSTEM,
  RV_INSTRUCTION_CLASS_FLOATING_POINT,
  RV_INSTRUCTION_CLASS_ATOMIC,
  RV_INSTRUCTION_CLASS_COUNT,
} RvInstructionClass;

typedef enum {
  RV_OPERATION_ILLEGAL_INSTRUCTION = 0,

  /* RV64I integer computational instructions. */
  RV_OPERATION_ADDI,
  RV_OPERATION_SLTI,
  RV_OPERATION_SLTIU,
  RV_OPERATION_XORI,
  RV_OPERATION_ORI,
  RV_OPERATION_ANDI,
  RV_OPERATION_SLLI,
  RV_OPERATION_SRLI,
  RV_OPERATION_SRAI,
  RV_OPERATION_ADDIW,
  RV_OPERATION_SLLIW,
  RV_OPERATION_SRLIW,
  RV_OPERATION_SRAIW,
  RV_OPERATION_ADD,
  RV_OPERATION_SUB,
  RV_OPERATION_SLL,
  RV_OPERATION_SLT,
  RV_OPERATION_SLTU,
  RV_OPERATION_XOR,
  RV_OPERATION_SRL,
  RV_OPERATION_SRA,
  RV_OPERATION_OR,
  RV_OPERATION_AND,
  RV_OPERATION_ADDW,
  RV_OPERATION_SUBW,
  RV_OPERATION_SLLW,
  RV_OPERATION_SRLW,
  RV_OPERATION_SRAW,

  /* RV64M multiplication and division instructions. */
  RV_OPERATION_MUL,
  RV_OPERATION_MULH,
  RV_OPERATION_MULHSU,
  RV_OPERATION_MULHU,
  RV_OPERATION_DIV,
  RV_OPERATION_DIVU,
  RV_OPERATION_REM,
  RV_OPERATION_REMU,
  RV_OPERATION_MULW,
  RV_OPERATION_DIVW,
  RV_OPERATION_DIVUW,
  RV_OPERATION_REMW,
  RV_OPERATION_REMUW,

  /* Zba/Zbb/Zbc/Zbs immediate instructions. */
  RV_OPERATION_BSETI,
  RV_OPERATION_BCLRI,
  RV_OPERATION_BINVI,
  RV_OPERATION_CLZ,
  RV_OPERATION_CTZ,
  RV_OPERATION_CPOP,
  RV_OPERATION_SEXT_B,
  RV_OPERATION_SEXT_H,
  RV_OPERATION_RORI,
  RV_OPERATION_BEXTI,
  RV_OPERATION_ORC_B,
  RV_OPERATION_REV8,
  RV_OPERATION_SLLI_UW,
  RV_OPERATION_CLZW,
  RV_OPERATION_CTZW,
  RV_OPERATION_CPOPW,
  RV_OPERATION_RORIW,

  /* Zba/Zbb/Zbc/Zbs register-register instructions. */
  RV_OPERATION_SH1ADD,
  RV_OPERATION_SH2ADD,
  RV_OPERATION_SH3ADD,
  RV_OPERATION_ANDN,
  RV_OPERATION_ORN,
  RV_OPERATION_XNOR,
  RV_OPERATION_ROL,
  RV_OPERATION_ROR,
  RV_OPERATION_MIN,
  RV_OPERATION_MINU,
  RV_OPERATION_MAX,
  RV_OPERATION_MAXU,
  RV_OPERATION_CLMUL,
  RV_OPERATION_CLMULR,
  RV_OPERATION_CLMULH,
  RV_OPERATION_BSET,
  RV_OPERATION_BCLR,
  RV_OPERATION_BEXT,
  RV_OPERATION_BINV,
  RV_OPERATION_ADD_UW,
  RV_OPERATION_SH1ADD_UW,
  RV_OPERATION_SH2ADD_UW,
  RV_OPERATION_SH3ADD_UW,
  RV_OPERATION_ZEXT_H,
  RV_OPERATION_ROLW,
  RV_OPERATION_RORW,

  /* RV64I loads and stores. */
  RV_OPERATION_LB,
  RV_OPERATION_LH,
  RV_OPERATION_LW,
  RV_OPERATION_LD,
  RV_OPERATION_LBU,
  RV_OPERATION_LHU,
  RV_OPERATION_LWU,
  RV_OPERATION_SB,
  RV_OPERATION_SH,
  RV_OPERATION_SW,
  RV_OPERATION_SD,

  /* RV64I control transfer and upper-immediate instructions. */
  RV_OPERATION_BEQ,
  RV_OPERATION_BNE,
  RV_OPERATION_BLT,
  RV_OPERATION_BGE,
  RV_OPERATION_BLTU,
  RV_OPERATION_BGEU,
  RV_OPERATION_JAL,
  RV_OPERATION_JALR,
  RV_OPERATION_LUI,
  RV_OPERATION_AUIPC,

  /* Memory ordering and privileged/system instructions. */
  RV_OPERATION_FENCE,
  RV_OPERATION_FENCE_I,
  RV_OPERATION_ECALL,
  RV_OPERATION_EBREAK,
  RV_OPERATION_SRET,
  RV_OPERATION_MRET,
  RV_OPERATION_WFI,
  RV_OPERATION_SFENCE_VMA,
  RV_OPERATION_CSRRW,
  RV_OPERATION_CSRRS,
  RV_OPERATION_CSRRC,
  RV_OPERATION_CSRRWI,
  RV_OPERATION_CSRRSI,
  RV_OPERATION_CSRRCI,

  /* 具体 C mnemonic 与寄存器文件保存在共享 compressed descriptor。 */
  RV_OPERATION_COMPRESSED,

  /* 具体 F/D mnemonic、寄存器文件与舍入字段保存在共享 floating descriptor。 */
  RV_OPERATION_FLOATING,

  /* 具体 LR/SC/AMO mnemonic、宽度与 aq/rl 保存在共享 atomic descriptor。 */
  RV_OPERATION_ATOMIC,
  RV_OPERATION_COUNT,
} RvOperation;

typedef struct {
  uint32_t encoding;
  word_t immediate;
  RvInstructionClass instruction_class;
  RvOperation operation;
  RiscvSystemInstruction system;
  uint8_t length;
  uint8_t rd;
  uint8_t rs1;
  uint8_t rs2;
  uint8_t rs3;
  RiscvAtomicInstruction atomic;
  RiscvCompressedInstruction compressed;
  RiscvFloatingInstruction floating;
} RvDecodedInstruction;

static inline bool rv_decode_cache_lookup(vaddr_t pc, uint32_t encoding,
                                          RvDecodedInstruction *instruction);
static inline void rv_decode_cache_insert(
    vaddr_t pc, const RvDecodedInstruction *instruction);
static inline void rv_decode_cache_flush(void);

#endif
