.DEFAULT_GOAL := run
.PHONY: all run negative pipeline-matrix admission-matrix
all run negative pipeline-matrix admission-matrix:
	@$(MAKE) --no-print-directory -C chengyue64 $@
%:
	@$(MAKE) --no-print-directory -C chengyue64 $@
