`include "define.v"
`include "common/OooSlotFacts.v"

// OooMemoryAccess: OoO core 子系统 wrapper（纯结构聚合，从 OooCoreTopGlue 抽出 2 个实例）。
// 行为与原扁平实例化等价：仅把跨边界信号导出为端口，内部信号下沉。
module OooMemoryAccess (
  input backend_drained_q,
  input checkpoint_mem_flush_q,
  input clk,
  input core_local_flush_w,
  input [`XLEN-1:0] core_mem_req_addr_w,
  input core_mem_req_valid_w,
  input [`XLEN-1:0] core_mem_req_wdata_w,
  input core_mem_req_write_w,
  input [`STRB_W-1:0] core_mem_req_wstrb_w,
  input core_mem_rsp_ready_w,
  input csr_trap_mem_valid_w,
  input flush_i,
  input head1_mem_raw_w,
  input [`INST_W-1:0] head_inst1_w,
  input [`XLEN-1:0] head_next_pc1_w,
  input [`XLEN-1:0] head_pc1_w,
  input mem_dispatch_fire_w,
  input mem_req_ready_i,
  input mem_rsp_valid_i,
  input orphan_stop_pending_w,
  input [`XLEN-1:0] pending_fp_mem_aligned_addr_w,
  input pending_fp_mem_done_q,
  input pending_fp_mem_pending_q,
  input [`XLEN-1:0] pending_fp_mem_wdata_w,
  input [`STRB_W-1:0] pending_fp_mem_wstrb_w,
  input pending_fp_q,
  input pending_fp_store_q,
  input pending_mem_capture_lane1_w,
  input pending_mem_clear_w,
  input pending_system_satp_write_commit_w,
  input pending_system_sfence_commit_w,
  input rst,
  input stop_pending_q,
  output mem_flush_o,
  output [`XLEN-1:0] mem_req_addr_o,
  output mem_req_valid_o,
  output [`XLEN-1:0] mem_req_wdata_o,
  output mem_req_write_o,
  output [`STRB_W-1:0] mem_req_wstrb_o,
  output mem_rsp_ready_o,
  output mmu_flush_o,
  output pending_fp_mem_req_fire_w,
  output pending_fp_mem_rsp_fire_w,
  output pending_mem_dispatched_q,
  output [`INST_W-1:0] pending_mem_inst_q,
  output [`XLEN-1:0] pending_mem_next_pc_q,
  output [`XLEN-1:0] pending_mem_pc_q,
  output pending_mem_q
);

  wire pending_fp_mem_req_valid_w;

  OooPendingMemorySequencer u_pending_memory_sequencer (
    .clk(clk),
    .rst(rst || flush_i),
    .late_clear_i(csr_trap_mem_valid_w),
    .clear_i(pending_mem_clear_w),
    .clear_dispatched_i(orphan_stop_pending_w),
    .dispatch_fire_i(mem_dispatch_fire_w),
    .capture_lane1_i(pending_mem_capture_lane1_w),
    .capture_valid_i(head1_mem_raw_w),
    .capture_pc_i(head_pc1_w),
    .capture_inst_i(head_inst1_w),
    .capture_next_pc_i(head_next_pc1_w),
    .valid_o(pending_mem_q),
    .dispatched_o(pending_mem_dispatched_q),
    .pc_o(pending_mem_pc_q),
    .inst_o(pending_mem_inst_q),
    .next_pc_o(pending_mem_next_pc_q)
  );


  OooMemoryRequestGate u_memory_request_gate (
    .core_local_flush_i(core_local_flush_w),
    .checkpoint_mem_flush_i(checkpoint_mem_flush_q),
    .pending_system_satp_write_commit_i(pending_system_satp_write_commit_w),
    .pending_system_sfence_commit_i(pending_system_sfence_commit_w),
    .stop_pending_i(stop_pending_q),
    .pending_fp_i(pending_fp_q),
    .backend_drained_i(backend_drained_q),
    .pending_fp_mem_pending_i(pending_fp_mem_pending_q),
    .pending_fp_mem_done_i(pending_fp_mem_done_q),
    .pending_fp_store_i(pending_fp_store_q),
    .pending_fp_mem_aligned_addr_i(pending_fp_mem_aligned_addr_w),
    .pending_fp_mem_wdata_i(pending_fp_mem_wdata_w),
    .pending_fp_mem_wstrb_i(pending_fp_mem_wstrb_w),
    .core_mem_req_valid_i(core_mem_req_valid_w),
    .core_mem_req_write_i(core_mem_req_write_w),
    .core_mem_req_addr_i(core_mem_req_addr_w),
    .core_mem_req_wdata_i(core_mem_req_wdata_w),
    .core_mem_req_wstrb_i(core_mem_req_wstrb_w),
    .core_mem_rsp_ready_i(core_mem_rsp_ready_w),
    .mem_req_ready_i(mem_req_ready_i),
    .mem_rsp_valid_i(mem_rsp_valid_i),
    .pending_fp_mem_req_valid_o(pending_fp_mem_req_valid_w),
    .pending_fp_mem_req_fire_o(pending_fp_mem_req_fire_w),
    .pending_fp_mem_rsp_fire_o(pending_fp_mem_rsp_fire_w),
    .mem_req_valid_o(mem_req_valid_o),
    .mem_req_write_o(mem_req_write_o),
    .mem_req_addr_o(mem_req_addr_o),
    .mem_req_wdata_o(mem_req_wdata_o),
    .mem_req_wstrb_o(mem_req_wstrb_o),
    .mem_rsp_ready_o(mem_rsp_ready_o),
    .mem_flush_o(mem_flush_o),
    .mmu_flush_o(mmu_flush_o)
  );

endmodule
