#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/../../.." && pwd)
RUN_DIR="$REPO_ROOT/.github/task-runs/2026-06-21-nemu-python-int-aslr-target-range-trace"
RUN_SUFFIX=${NEMU_TRACE_RUN_SUFFIX:-$(date +%Y%m%d-%H%M%S)}
EVIDENCE_DIR="$RUN_DIR/evidence/aslr-off-full-lite-int10-create-target-range-dual-$RUN_SUFFIX"

mkdir -p "$EVIDENCE_DIR"

set +e
NEMU_INTERPRETER_WIDE_IFETCH=0 \
NEMU_PC_GPR_TRACE=1 \
NEMU_PC_GPR_TRACE_START=${NEMU_PC_GPR_TRACE_START:-0x2aaab43a4a} \
NEMU_PC_GPR_TRACE_END=${NEMU_PC_GPR_TRACE_END:-0x2aaab43a90} \
NEMU_PC_GPR_TRACE_MAX=${NEMU_PC_GPR_TRACE_MAX:-8192} \
NEMU_PC_GPR_TRACE_USER_ONLY=${NEMU_PC_GPR_TRACE_USER_ONLY:-1} \
NEMU_FP_LOAD_TRACE=1 \
NEMU_FP_LOAD_TRACE_PC_START=${NEMU_FP_LOAD_TRACE_PC_START:-0x2aaab43a5e} \
NEMU_FP_LOAD_TRACE_PC_END=${NEMU_FP_LOAD_TRACE_PC_END:-0x2aaab43a5e} \
NEMU_FP_LOAD_TRACE_ADDR_START=${NEMU_FP_LOAD_TRACE_ADDR_START:-0x2aaaf2bc40} \
NEMU_FP_LOAD_TRACE_ADDR_END=${NEMU_FP_LOAD_TRACE_ADDR_END:-0x2aaaf2bc40} \
NEMU_FP_LOAD_TRACE_MAX=${NEMU_FP_LOAD_TRACE_MAX:-8192} \
NEMU_FP_LOAD_TRACE_USER_ONLY=${NEMU_FP_LOAD_TRACE_USER_ONLY:-1} \
NEMU_PADDR_WRITE_VALUE_TRACE=1 \
NEMU_PADDR_WRITE_VALUE_TRACE_VALUE=0xfff0000000000000 \
NEMU_PADDR_WRITE_VALUE_TRACE_MASK=0xffffffffffffffff \
NEMU_PADDR_WRITE_VALUE_TRACE_MAX=8192 \
NEMU_VADDR_WRITE_VALUE_TRACE=1 \
NEMU_VADDR_WRITE_VALUE_TRACE_VALUE=0xfff0000000000000 \
NEMU_VADDR_WRITE_VALUE_TRACE_MASK=0xffffffffffffffff \
NEMU_VADDR_WRITE_VALUE_TRACE_MAX=8192 \
NEMU_VADDR_WRITE_VALUE_TRACE_USER_ONLY=0 \
NEMU_VADDR_WRITE_TRACE=1 \
NEMU_VADDR_WRITE_TRACE_START=0x3ff7c98360 \
NEMU_VADDR_WRITE_TRACE_END=0x3ff7c98367 \
NEMU_VADDR_WRITE_TRACE_START2=0x3ff7ac04e0 \
NEMU_VADDR_WRITE_TRACE_END2=0x3ff7ac04e7 \
NEMU_VADDR_WRITE_TRACE_MAX=8192 \
NEMU_VADDR_WRITE_TRACE_USER_ONLY=1 \
make -C "$REPO_ROOT/Linux" ARCH=riscv64-nemu \
  NEMU_PYTHON_INT_CHECK_LOG_DIR="$EVIDENCE_DIR" \
  NEMU_PYTHON_INT_ROOTFS_OVERLAY="$EVIDENCE_DIR/rootfs-overlay.raw" \
  NEMU_PYTHON_INT_STAGE_MODE=full-lite \
  NEMU_PYTHON_INT_PROBE_MODE=int10-create \
  NEMU_PYTHON_INT_STAGE_PREWARM=0 \
  NEMU_PYTHON_INT_LOOPS=20 \
  NEMU_PYTHON_INT_DISABLE_ASLR=1 \
  NEMU_PYTHON_INT_CHECK_MAX_CYCLES=320000000000 \
  NEMU_PYTHON_INT_CHECK_TIMEOUT=9000 \
  NEMU_PYTHON_INT_BOOT_TIMEOUT=3600 \
  NEMU_PYTHON_INT_POWEROFF=0 \
  check-nemu-python-int-preflight >"$EVIDENCE_DIR/run.log" 2>&1
rc=$?
if [ -f "$EVIDENCE_DIR/console.log" ]; then
  python3 "$REPO_ROOT/Linux/tools/nemu-python-int-trace-correlate.py" \
    "$EVIDENCE_DIR/console.log" >"$EVIDENCE_DIR/trace-correlate.log" 2>&1
fi
set -e

printf '%s\n' "$rc" >"$EVIDENCE_DIR/run.rc"
exit "$rc"
