`include "define.v"
`include "common/OooSlotFacts.v"

// OooExecuteBackend: OoO core 子系统 wrapper（纯结构聚合，从 OooCoreTopGlue 抽出 4 个实例）。
// 行为与原扁平实例化等价：仅把跨边界信号导出为端口，内部信号下沉。
module OooExecuteBackend #(
  parameter PHY_REG_ADDR_W = `OOO_PHY_REG_ADDR_W,
  parameter ROB_INDEX_W = `OOO_ROB_INDEX_W,
  parameter ROB_COUNT_W = `OOO_ROB_COUNT_W,
  parameter FREE_COUNT_W = `OOO_FREE_COUNT_W,
  parameter ISSUE_COUNT_W = `OOO_ISSUE_COUNT_W
) (
  input clk,
  input core_checkpoint_capture_w,
  input core_checkpoint_quiesce_w,
  input core_checkpoint_restore_w,
  input core_commit1_block_w,
  input core_commit_ready_w,
  input [`XLEN-1:0] core_dispatch0_csr_rdata_w,
  input [2:0] frm_i,  // FP#1: fcsr.frm 路由,供 DYN 舍入
  input [`INST_W-1:0] core_dispatch0_inst_w,
  input [`XLEN-1:0] core_dispatch0_next_pc_w,
  input [`XLEN-1:0] core_dispatch0_pc_w,
  input core_dispatch0_valid_w,
  input [`XLEN-1:0] core_dispatch0_pred_npc_w,
  input [`BPU_BHT_INDEX_W-1:0] core_dispatch0_bht_idx_w,
  input core_dispatch0_pred_taken_w,
  input [`INST_W-1:0] core_dispatch1_inst_w,
  input [`XLEN-1:0] core_dispatch1_next_pc_w,
  input [`XLEN-1:0] core_dispatch1_pc_w,
  input core_dispatch1_valid_w,
  input [`XLEN-1:0] core_dispatch1_pred_npc_w,
  input [`BPU_BHT_INDEX_W-1:0] core_dispatch1_bht_idx_w,
  input core_dispatch1_pred_taken_w,
  input core_local_flush_w,
  input core_mem_issue_block_w,
  input csr_trap_mem_valid_w,
  input dispatch1_optional_w,
  input flush_i,
  input [`INST_W-1:0] head_inst0_w,
  input [`INST_W-1:0] head_inst1_w,
  input [`XLEN-1:0] head_next_pc0_w,
  input [`XLEN-1:0] head_next_pc1_w,
  input [`XLEN-1:0] head_pc1_w,
  input [`XLEN-1:0] head_pc_w,
  input mem_req_ready_i,
  input mem_rsp_error_i,
  input mem_rsp_page_fault_i,
  input [`XLEN-1:0] mem_rsp_rdata_i,
  input mem_rsp_valid_i,
  input mem_translate_active_i,
  input [2:0] pending_branch_cmp_op_q,
  input pending_branch_dispatched_q,
  input [`XLEN-1:0] pending_branch_pc_q,
  input pending_branch_q,
  input [`XLEN-1:0] pending_branch_rs1_data_w,
  input [`XLEN-1:0] pending_branch_rs2_data_w,
  input rst,
  input stop_pending_q,
  output [`XLEN-1:0] a0_data_w,
  output core_branch_resolve_misaligned_w,
  output [ROB_INDEX_W-1:0] core_branch_resolve_rob_idx_w,
  output core_branch_resolve_mispredict_w,
  output core_branch_resolve_is_branch_w,
  output core_branch_resolve_taken_w,
  output core_branch_resolve_pred_taken_w,
  output [`BPU_BHT_INDEX_W-1:0] core_branch_resolve_bht_idx_w,
  output [`XLEN-1:0] core_branch_resolve_next_pc_w,
  output [`XLEN-1:0] core_branch_resolve_pc_w,
  output core_branch_resolve_valid_w,
  output [`TRAP_CAUSE_W-1:0] core_commit0_cause_w,
  output core_commit0_exception_w,
  output [`INST_W-1:0] core_commit0_inst_w,
  output [`XLEN-1:0] core_commit0_next_pc_w,
  output [`XLEN-1:0] core_commit0_pc_w,
  output [`REG_ADDR_W-1:0] core_commit0_rd_addr_w,
  output [`XLEN-1:0] core_commit0_rd_data_w,
  output core_commit0_rd_en_w,
  output [`XLEN-1:0] core_commit0_tval_w,
  output core_commit0_valid_w,
  output core_commit0_write_w,
  output [`TRAP_CAUSE_W-1:0] core_commit1_cause_w,
  output core_commit1_exception_w,
  output [`INST_W-1:0] core_commit1_inst_w,
  output [`XLEN-1:0] core_commit1_next_pc_w,
  output [`XLEN-1:0] core_commit1_pc_w,
  output [`REG_ADDR_W-1:0] core_commit1_rd_addr_w,
  output [`XLEN-1:0] core_commit1_rd_data_w,
  output core_commit1_rd_en_w,
  output [`XLEN-1:0] core_commit1_tval_w,
  output core_commit1_valid_w,
  output core_commit1_write_w,
  output [`XLEN * `REG_NUM - 1:0] core_debug_gprs_w,
  output core_dispatch_branch_resolve_misaligned_w,
  output [`XLEN-1:0] core_dispatch_branch_resolve_next_pc_w,
  output [`XLEN-1:0] core_dispatch_branch_resolve_pc_w,
  output core_dispatch_branch_resolve_valid_w,
  output core_mem_idle_w,
  output core_mem_retire_quiet_w,
  output [4:0] core_commit0_fflags_w,
  output core_commit0_is_fp_rd_w,
  output core_commit1_is_fp_rd_w,
  output [4:0] core_commit1_fflags_w,
  output [`XLEN-1:0] core_mem_req_addr_w,
  output core_mem_req_valid_w,
  output [`XLEN-1:0] core_mem_req_wdata_w,
  output core_mem_req_write_w,
  output core_mem_req_probe_w,
  output core_mem_req_pretrans_w,
  output core_mem_req_nokill_w,
  output [`STRB_W-1:0] core_mem_req_wstrb_w,
  output core_mem_rsp_ready_w,
  output [1:0] core_retire_count_w,
  output dispatch0_ready_w,
  output dispatch0_unsupported_w,
  output dispatch0_unsupported_raw_w,
  output dispatch1_ready_w,
  output dispatch1_unsupported_w,
  output dispatch1_unsupported_raw_w,
  output execute0_valid_unused_w,
  output execute1_valid_unused_w,
  output [FREE_COUNT_W-1:0] free_count_o,
  output [ISSUE_COUNT_W-1:0] issue_count_o,
  output pending_branch_taken_w,
  output [ROB_COUNT_W-1:0] rob_count_o
);



  CompareUnit u_pending_branch_compare (
    .lhs_i(pending_branch_rs1_data_w),
    .rhs_i(pending_branch_rs2_data_w),
    .cmp_op_i(pending_branch_cmp_op_q),
    .cmp_true_o(pending_branch_taken_w)
  );


  OooAluCoreSlice #(
    .PHY_REG_ADDR_W(PHY_REG_ADDR_W),
    .ROB_INDEX_W(ROB_INDEX_W),
    .ROB_COUNT_W(ROB_COUNT_W),
    .FREE_COUNT_W(FREE_COUNT_W),
    .ISSUE_COUNT_W(ISSUE_COUNT_W)
  ) u_core_slice (
    .clk(clk),
    .rst(rst),
    .flush_i(core_local_flush_w),
    .checkpoint_capture_i(core_checkpoint_capture_w),
    .checkpoint_restore_i(core_checkpoint_restore_w),
    .checkpoint_quiesce_i(core_checkpoint_quiesce_w),
    .mem_issue_block_i(core_mem_issue_block_w),
    .pending_branch_fast_valid_i(stop_pending_q && pending_branch_q &&
                                 pending_branch_dispatched_q),
    .pending_branch_fast_pc_i(pending_branch_pc_q),
    // 【B-FP 簇】pending-FP 壳已拆: FP GPR 结果走正常 wb, 串行写口封 0。
    .serial_write_valid_i(1'b0),
    .serial_write_arch_rd_i({`REG_ADDR_W{1'b0}}),
    .serial_write_data_i({`XLEN{1'b0}}),
    .dispatch0_valid_i(core_dispatch0_valid_w),
    .dispatch0_ready_o(dispatch0_ready_w),
    .dispatch0_pc_i(core_dispatch0_pc_w),
    .dispatch0_next_pc_i(core_dispatch0_next_pc_w),
    .dispatch0_pred_npc_i(core_dispatch0_pred_npc_w),
    .dispatch0_bht_idx_i(core_dispatch0_bht_idx_w),
    .dispatch0_pred_taken_i(core_dispatch0_pred_taken_w),
    .dispatch0_inst_i(core_dispatch0_inst_w),
    .dispatch0_csr_rdata_i(core_dispatch0_csr_rdata_w),
    .dispatch0_unsupported_o(dispatch0_unsupported_w),
    .dispatch0_unsupported_raw_o(dispatch0_unsupported_raw_w),
    .dispatch1_valid_i(core_dispatch1_valid_w),
    .dispatch1_optional_i(dispatch1_optional_w),
    .dispatch1_ready_o(dispatch1_ready_w),
    .dispatch1_pc_i(core_dispatch1_pc_w),
    .dispatch1_next_pc_i(core_dispatch1_next_pc_w),
    .dispatch1_pred_npc_i(core_dispatch1_pred_npc_w),
    .dispatch1_bht_idx_i(core_dispatch1_bht_idx_w),
    .dispatch1_pred_taken_i(core_dispatch1_pred_taken_w),
    .dispatch1_inst_i(core_dispatch1_inst_w),
    .dispatch1_csr_rdata_i({`XLEN{1'b0}}),
    .dispatch1_unsupported_o(dispatch1_unsupported_w),
    .dispatch1_unsupported_raw_o(dispatch1_unsupported_raw_w),
    .mem_req_valid_o(core_mem_req_valid_w),
    .mem_req_ready_i(mem_req_ready_i),
    .mem_req_write_o(core_mem_req_write_w),
    .mem_req_probe_o(core_mem_req_probe_w),
    .mem_req_pretrans_o(core_mem_req_pretrans_w),
    .mem_req_nokill_o(core_mem_req_nokill_w),
    .mem_req_addr_o(core_mem_req_addr_w),
    .mem_req_wdata_o(core_mem_req_wdata_w),
    .mem_req_wstrb_o(core_mem_req_wstrb_w),
    .mem_rsp_valid_i(mem_rsp_valid_i),
    .mem_rsp_ready_o(core_mem_rsp_ready_w),
    .mem_rsp_rdata_i(mem_rsp_rdata_i),
    .mem_rsp_error_i(mem_rsp_error_i),
    .mem_rsp_page_fault_i(mem_rsp_page_fault_i),
    .mem_translate_active_i(mem_translate_active_i),
    .mem_retire_quiet_o(core_mem_retire_quiet_w),
    .commit0_fflags_o(core_commit0_fflags_w),
    .commit0_is_fp_rd_o(core_commit0_is_fp_rd_w),
    .commit1_is_fp_rd_o(core_commit1_is_fp_rd_w),
    .commit1_fflags_o(core_commit1_fflags_w),
    .frm_i(frm_i),
    .commit_ready_i(core_commit_ready_w),
    .commit1_block_i(core_commit1_block_w),
    .commit0_valid_o(core_commit0_valid_w),
    .commit0_pc_o(core_commit0_pc_w),
    .commit0_next_pc_o(core_commit0_next_pc_w),
    .commit0_inst_o(core_commit0_inst_w),
    .commit0_rd_en_o(core_commit0_rd_en_w),
    .commit0_arch_rd_o(core_commit0_rd_addr_w),
    .commit0_data_o(core_commit0_rd_data_w),
    .commit0_exception_o(core_commit0_exception_w),
    .commit0_cause_o(core_commit0_cause_w),
    .commit0_tval_o(core_commit0_tval_w),
    .commit0_write_o(core_commit0_write_w),
    .commit1_valid_o(core_commit1_valid_w),
    .commit1_pc_o(core_commit1_pc_w),
    .commit1_next_pc_o(core_commit1_next_pc_w),
    .commit1_inst_o(core_commit1_inst_w),
    .commit1_rd_en_o(core_commit1_rd_en_w),
    .commit1_arch_rd_o(core_commit1_rd_addr_w),
    .commit1_data_o(core_commit1_rd_data_w),
    .commit1_exception_o(core_commit1_exception_w),
    .commit1_cause_o(core_commit1_cause_w),
    .commit1_tval_o(core_commit1_tval_w),
    .commit1_write_o(core_commit1_write_w),
    .free_count_o(free_count_o),
    .rob_count_o(rob_count_o),
	    .issue_count_o(issue_count_o),
	    .mem_idle_o(core_mem_idle_w),
	    .execute0_valid_o(execute0_valid_unused_w),
	    .execute1_valid_o(execute1_valid_unused_w),
	    .branch_resolve_valid_o(core_branch_resolve_valid_w),
	    .branch_resolve_pc_o(core_branch_resolve_pc_w),
	    .branch_resolve_next_pc_o(core_branch_resolve_next_pc_w),
	    .branch_resolve_misaligned_o(core_branch_resolve_misaligned_w),
	    .branch_resolve_rob_idx_o(core_branch_resolve_rob_idx_w),
	    .branch_resolve_mispredict_o(core_branch_resolve_mispredict_w),
	    .branch_resolve_is_branch_o(core_branch_resolve_is_branch_w),
	    .branch_resolve_taken_o(core_branch_resolve_taken_w),
	    .branch_resolve_pred_taken_o(core_branch_resolve_pred_taken_w),
	    .branch_resolve_bht_idx_o(core_branch_resolve_bht_idx_w),
	    .dispatch_branch_resolve_valid_o(core_dispatch_branch_resolve_valid_w),
	    .dispatch_branch_resolve_pc_o(core_dispatch_branch_resolve_pc_w),
	    .dispatch_branch_resolve_next_pc_o(core_dispatch_branch_resolve_next_pc_w),
	    .dispatch_branch_resolve_misaligned_o(core_dispatch_branch_resolve_misaligned_w),
	    .retire_count_o(core_retire_count_w),
    .a0_data_o(a0_data_w),
    .debug_gprs_o(core_debug_gprs_w)
  );

endmodule
