# Native two-wide RV64 source list, shared by simulation and synthesis.
R64_RTL_ROOT := $(abspath $(dir $(lastword $(MAKEFILE_LIST))))
R64_RTL_SRCS := \
  $(R64_RTL_ROOT)/frontend/R64FetchStream.v \
  $(R64_RTL_ROOT)/frontend/R64Align.v \
  $(R64_RTL_ROOT)/frontend/R64PacketParse.v \
  $(R64_RTL_ROOT)/frontend/R64Rvc.v \
  $(R64_RTL_ROOT)/frontend/R64Predictor.v \
  $(R64_RTL_ROOT)/frontend/R64Frontend.v \
  $(R64_RTL_ROOT)/backend/R64Decode.v \
  $(R64_RTL_ROOT)/backend/R64DecodeControl.v \
  $(R64_RTL_ROOT)/backend/R64DecodeStage.v \
  $(R64_RTL_ROOT)/backend/R64Rob.v \
  $(R64_RTL_ROOT)/backend/R64FreeSelect.v \
  $(R64_RTL_ROOT)/backend/R64Rename.v \
  $(R64_RTL_ROOT)/backend/R64Issue.v \
  $(R64_RTL_ROOT)/backend/R64RegRead.v \
  $(R64_RTL_ROOT)/backend/R64FpReadPlan.v \
  $(R64_RTL_ROOT)/backend/R64Writeback.v \
  $(R64_RTL_ROOT)/backend/R64Execute.v \
  $(R64_RTL_ROOT)/backend/R64Backend.v \
  $(R64_RTL_ROOT)/backend/R64Alu.v \
  $(R64_RTL_ROOT)/backend/R64ProductTree.v \
  $(R64_RTL_ROOT)/backend/R64CarryStages.v \
  $(R64_RTL_ROOT)/backend/R64WideAdd.v \
  $(R64_RTL_ROOT)/backend/R64NumericOwner.v \
  $(R64_RTL_ROOT)/backend/R64Multiply.v \
  $(R64_RTL_ROOT)/backend/R64Divide.v \
  $(R64_RTL_ROOT)/backend/R64Clmul.v \
  $(R64_RTL_ROOT)/fp/R64FpOperand.v \
  $(R64_RTL_ROOT)/fp/R64FpUnpack.v \
  $(R64_RTL_ROOT)/fp/R64FpRoundStages.v \
  $(R64_RTL_ROOT)/fp/R64FpRound.v \
  $(R64_RTL_ROOT)/fp/R64FpProductPipe.v \
  $(R64_RTL_ROOT)/fp/R64FpFma.v \
  $(R64_RTL_ROOT)/fp/R64FpLong.v \
  $(R64_RTL_ROOT)/fp/R64FpFast.v \
  $(R64_RTL_ROOT)/fp/R64FpCompletion.v \
  $(R64_RTL_ROOT)/fp/R64FpExecute.v \
  $(R64_RTL_ROOT)/core/R64CoreTop.v \
  $(R64_RTL_ROOT)/control/R64Commit.v \
  $(R64_RTL_ROOT)/control/R64CsrDecode.v \
  $(R64_RTL_ROOT)/control/R64TrapVector.v \
  $(R64_RTL_ROOT)/control/R64Counter.v \
  $(R64_RTL_ROOT)/control/R64CounterNear.v \
  $(R64_RTL_ROOT)/control/R64Trigger.v \
  $(R64_RTL_ROOT)/control/R64Csr.v \
  $(R64_RTL_ROOT)/control/R64Serial.v \
  $(R64_RTL_ROOT)/memory/R64PmpDecode.v \
  $(R64_RTL_ROOT)/memory/R64PmpCheck.v \
  $(R64_RTL_ROOT)/memory/R64Memory.v \
  $(R64_RTL_ROOT)/memory/R64PtePort.v \
  $(R64_RTL_ROOT)/memory/R64Pma.v \
  $(R64_RTL_ROOT)/memory/R64PmaRange.v \
  $(R64_RTL_ROOT)/memory/R64FetchProtection.v \
  $(R64_RTL_ROOT)/memory/R64DataProtection.v \
  $(R64_RTL_ROOT)/memory/R64Tlb.v \
  $(R64_RTL_ROOT)/memory/R64PageWalk.v \
  $(R64_RTL_ROOT)/memory/R64Translation.v \
  $(R64_RTL_ROOT)/memory/R64FetchTranslation.v \
  $(R64_RTL_ROOT)/memory/R64DataTranslation.v \
  $(R64_RTL_ROOT)/memory/R64ICache.v \
  $(R64_RTL_ROOT)/bus/R64AxiRead.v \
  $(R64_RTL_ROOT)/bus/R64AxiWrite.v \
  $(R64_RTL_ROOT)/lsu/R64LsuOrderSelect.v \
  $(R64_RTL_ROOT)/lsu/R64LsuSelect.v \
  $(R64_RTL_ROOT)/lsu/R64LsuForwardByte.v \
  $(R64_RTL_ROOT)/lsu/R64LsuYoungestByte.v \
  $(R64_RTL_ROOT)/lsu/R64LsuRequestQueue.v \
  $(R64_RTL_ROOT)/lsu/R64LsuMetaRead.v \
  $(R64_RTL_ROOT)/lsu/R64LsuCompletion.v \
  $(R64_RTL_ROOT)/lsu/R64Lsu.v \
  $(R64_RTL_ROOT)/lsu/R64MemoryService.v \
  $(R64_RTL_ROOT)/lsu/R64Dcache.v \
  $(R64_RTL_ROOT)/lsu/R64DcacheAmoParts.v \
  $(R64_RTL_ROOT)/lsu/R64MemorySplit.v \
  $(R64_RTL_ROOT)/lsu/R64LoadStore.v \
  $(R64_RTL_ROOT)/platform/R64TensorMemory.v \
  $(R64_RTL_ROOT)/platform/R64AxiReadService.v \
  $(R64_RTL_ROOT)/platform/R64AxiFabric.v \
  $(R64_RTL_ROOT)/platform/R64AxiRegisterPort.v \
  $(R64_RTL_ROOT)/platform/R64AxiRtc.v \
  $(R64_RTL_ROOT)/platform/R64AxiPlatform.v \
  $(R64_RTL_ROOT)/platform/R64SystemTop.v \
  $(R64_RTL_ROOT)/../bus/AxiClint.v \
  $(R64_RTL_ROOT)/../bus/AxiPlic.v \
  $(R64_RTL_ROOT)/../bus/AxiResetSyscon.v \
  $(R64_RTL_ROOT)/../bus/AxiToUart.v \
  $(R64_RTL_ROOT)/../bus/Uart.v \
  $(R64_RTL_ROOT)/../bus/AxiDefaultSlave.v
