R64_TENSOR_RTL_ROOT := $(abspath $(dir $(lastword $(MAKEFILE_LIST))))
R64_TENSOR_WORKSPACE := $(abspath $(R64_TENSOR_RTL_ROOT)/../../../..)
# Real NPU numerical engines; functional DPI and host portals are disabled.
R64_TENSOR_SRCS := $(R64_TENSOR_WORKSPACE)/npu/version_0820/third_party/fpu-sp/verilog/src/lzc/lzc_wire.sv \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/third_party/fpu-sp/verilog/src/float/fp_wire.sv \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/third_party/hardfloat/source/RISCV/HardFloat_specialize.v \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/third_party/hardfloat/source/HardFloat_primitives.v \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/third_party/hardfloat/source/HardFloat_rawFN.v \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/third_party/hardfloat/source/isSigNaNRecFN.v \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/third_party/hardfloat/source/fNToRecFN.v \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/third_party/hardfloat/source/recFNToFN.v \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/third_party/hardfloat/source/recFNToRecFN.v \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/third_party/hardfloat/source/recFNToIN.v \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/third_party/hardfloat/source/iNToRecFN.v \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/third_party/hardfloat/source/mulAddRecFN.v \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/third_party/hardfloat/source/addRecFN.v \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/rtl/TensorNpuFp16ToFp32.v \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/rtl/TensorNpuInt32ToFp32.v \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/rtl/TensorNpuFp32AddMul.v \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/rtl/TensorNpuFp32Div.v \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/rtl/TensorNpuFp32ToFp16.v \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/rtl/TensorNpuFp32ToInt32Rmm.v \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/rtl/TensorNpuQ8DequantBlock.v \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/rtl/TensorNpuQ8GetRowsEngine.v \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/rtl/TensorNpuQ8GetRowsWritebackAdapter.v \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/rtl/TensorNpuQ8DotEngine.v \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/rtl/TensorNpuQ8ScaleAccumulator.v \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/rtl/TensorNpuQ8ReferenceQuantizer.v \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/rtl/TensorNpuQ8StreamGemv.v \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/rtl/TensorNpuQ8GemvWritebackAdapter.v \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/rtl/TensorNpuQ8RowSimdCore.v \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/rtl/TensorNpuQ8GemvPortalAdapter.v \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/rtl/TensorNpuF32GatherRepeatAdapter.v \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/rtl/TensorNpuF32TensorAlu.v \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/rtl/TensorNpuVectorF32Adapter.v \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/rtl/TensorNpuF32AluSimdCore.v \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/rtl/TensorNpuF32AluPortalAdapter.v \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/rtl/TensorNpuF32GatherRepeatPortalAdapter.v \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/rtl/TensorNpuFp32ToFp64.v \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/rtl/TensorNpuFp64Fma.v \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/rtl/TensorNpuFp64ToInt32Rmm.v \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/rtl/TensorNpuInt32ToFp64.v \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/rtl/TensorNpuFp64ToFp32Finite.v \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/rtl/TensorNpuAorExp32.v \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/rtl/TensorNpuAorLog32.v \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/rtl/TensorNpuUnaryGluElement.v \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/rtl/TensorNpuUnaryGluWritebackAdapter.v \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/rtl/TensorNpuFp32Sqrt.v \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/rtl/TensorNpuFp64Add.v \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/rtl/TensorNpuFp64ToFp32.v \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/rtl/TensorNpuFp32SquareSum64.v \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/rtl/TensorNpuFp64Pow2Scale.v \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/rtl/TensorNpuNormEngine.v \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/rtl/TensorNpuNormWritebackAdapter.v \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/rtl/TensorNpuFp32ToFp64Ieee.v \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/rtl/TensorNpuFp64AddIeee.v \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/rtl/TensorNpuFp64ToFp32Ieee.v \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/rtl/TensorNpuOrderedSumRows.v \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/rtl/TensorNpuSumRowsWritebackAdapter.v \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/rtl/TensorNpuSsmConvWritebackAdapter.v \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/rtl/TensorNpuTensorMover.v \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/rtl/TensorNpuSetRowsEngine.v \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/rtl/TensorNpuMoverSetRowsWritebackAdapter.v \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/rtl/TensorNpuFp32Fma.v \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/rtl/TensorNpuF16AttentionMatmulWritebackAdapter.v \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/rtl/TensorNpuSoftmaxWritebackAdapter.v \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/rtl/TensorNpuFp32SincosCordic.v \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/rtl/TensorNpuRopeWritebackAdapter.v \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/rtl/TensorNpuCoprocessor.v \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/rtl/TensorNpuCommandDecoder.v \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/rtl/TensorNpuRegisterFile.v \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/rtl/TensorNpuMm2Engine.v \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/rtl/TensorNpuDmaEngine.v \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/rtl/TensorNpuLocalMemory.v \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/third_party/fpu-sp/verilog/src/lzc/lzc_16.sv \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/third_party/fpu-sp/verilog/src/lzc/lzc_8.sv \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/third_party/fpu-sp/verilog/src/lzc/lzc_128.sv \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/third_party/fpu-sp/verilog/src/lzc/lzc_4.sv \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/third_party/fpu-sp/verilog/src/lzc/lzc_64.sv \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/third_party/fpu-sp/verilog/src/lzc/lzc_32.sv \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/third_party/fpu-sp/verilog/src/float/fp_ext.sv \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/third_party/fpu-sp/verilog/src/float/fp_cvt.sv \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/third_party/fpu-sp/verilog/src/float/fp_cmp.sv \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/third_party/fpu-sp/verilog/src/float/fp_fdiv.sv \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/third_party/fpu-sp/verilog/src/float/fp_mac.sv \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/third_party/fpu-sp/verilog/src/float/fp_unit.sv \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/third_party/fpu-sp/verilog/src/float/fp_sgnj.sv \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/third_party/fpu-sp/verilog/src/float/fp_rnd.sv \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/third_party/fpu-sp/verilog/src/float/fp_exe.sv \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/third_party/fpu-sp/verilog/src/float/fp_max.sv \
 $(R64_TENSOR_WORKSPACE)/npu/version_0820/third_party/fpu-sp/verilog/src/float/fp_fma.sv \
 $(R64_TENSOR_RTL_ROOT)/platform/R64TensorLink.v \
 $(R64_TENSOR_RTL_ROOT)/platform/R64TensorSystemTop.v
R64_TENSOR_INCLUDES := -I$(R64_TENSOR_WORKSPACE)/npu/version_0820/rtl -I$(R64_TENSOR_WORKSPACE)/npu/version_0820/third_party/hardfloat/source -I$(R64_TENSOR_WORKSPACE)/npu/version_0820/third_party/hardfloat/source/RISCV
