# NPC RTL source catalog.
# 按功能目录集中维护 filelist，主仿真、模块 testbench 和综合入口共享同一份路径清单。

VSRCDIR ?= $(abspath ./vsrc)

RTL_INCLUDE_DIR := $(VSRCDIR)/include
RTL_COMMON_DIR := $(VSRCDIR)/common
RTL_CORE_DIR := $(VSRCDIR)/core
RTL_FRONTEND_DIR := $(VSRCDIR)/frontend
RTL_DECODE_DIR := $(VSRCDIR)/decode
RTL_EXECUTE_DIR := $(VSRCDIR)/execute
RTL_MEMORY_DIR := $(VSRCDIR)/memory
RTL_CACHE_DIR := $(VSRCDIR)/cache
RTL_RENAME_ALLOCATE_DIR := $(VSRCDIR)/rename_allocate
RTL_SCHEDULING_DIR := $(VSRCDIR)/scheduling
RTL_REGREAD_BYPASS_DIR := $(VSRCDIR)/regread_bypass
RTL_CONTROL_DIR := $(VSRCDIR)/control
RTL_BUS_DIR := $(VSRCDIR)/bus
RTL_WRITEBACK_DIR := $(VSRCDIR)/writeback
RTL_SIM_DIR := $(VSRCDIR)/sim
RTL_DEBUG_DIR := $(VSRCDIR)/debug
# SRAM 宏行为模型独立目录：仿真真源；NpcTop 综合时按模块名进 SYNTH_BLACKBOX_MODULES。
RTL_SRAM_DIR := $(VSRCDIR)/sram
# 级间边界原语独立目录：PipeStageReg 等(自带 keep_hierarchy)；治理 spec 见 design/arch/pipeline-stage-boundary.md。
RTL_PIPELINE_DIR := $(VSRCDIR)/pipeline

RTL_DEFINE := $(RTL_INCLUDE_DIR)/define.v
RTL_OOO_SLOT_FACTS_V := $(RTL_COMMON_DIR)/OooSlotFacts.v


RTL_OOO_SV39_TLB := $(RTL_MEMORY_DIR)/OooSv39Tlb.v
RTL_OOO_FETCH_PACKET_CACHE := $(RTL_CACHE_DIR)/OooFetchPacketCache.v
RTL_OOO_DATA_WORD_CACHE := $(RTL_CACHE_DIR)/OooDataWordCache.v
RTL_SRAM_FETCH_PACKET := $(RTL_SRAM_DIR)/Sram4096x199.v
RTL_SRAM_DATA_WORD := $(RTL_SRAM_DIR)/Sram4096x113.v
RTL_PIPE_STAGE_REG := $(RTL_PIPELINE_DIR)/PipeStageReg.v
RTL_OOO_BRANCH_DIRECTION_PREDICTOR := $(RTL_FRONTEND_DIR)/OooBranchDirectionPredictor.v

RTL_NPC_CORE_TOP := $(RTL_CORE_DIR)/NpcCoreTop.v
RTL_NPC_TOP := $(RTL_CORE_DIR)/NpcTop.v
RTL_OOO_FETCH_AXI_BRIDGE := $(RTL_FRONTEND_DIR)/OooFetchAxiBridge.v
RTL_OOO_MEM_AXI_BRIDGE := $(RTL_MEMORY_DIR)/OooMemAxiBridge.v
RTL_OOO_LSU_AXI_LANE_ADAPTER := $(RTL_MEMORY_DIR)/OooLsuAxiLaneAdapter.v
# F0 shared miss-fabric leaf.  It is compiled/linted from the common catalog
# but intentionally remains uninstantiated until the dual-memory data path lands.
RTL_OOO_DUAL_MEM_AXI_ARBITER := $(RTL_MEMORY_DIR)/OooDualMemAxiArbiter.v
# F1 architecture-prototype leaf.  It is compiled/linted from the common
# catalog but intentionally remains uninstantiated by the canonical core.
RTL_OOO_DUAL_MEM_BRIDGE_WRAPPER := $(RTL_MEMORY_DIR)/OooDualMemBridgeWrapper.v
RTL_CSR_FILE := $(RTL_CORE_DIR)/CsrFile.v


RTL_DECODE_STAGE := $(RTL_DECODE_DIR)/DecodeStage.v
RTL_DECODE_UNIT := $(RTL_DECODE_DIR)/DecodeUnit.v
RTL_IMM_GEN := $(RTL_DECODE_DIR)/ImmGen.v

RTL_ALU := $(RTL_EXECUTE_DIR)/ALU.v
RTL_COMPARE_UNIT := $(RTL_EXECUTE_DIR)/CompareUnit.v

RTL_LSU := $(RTL_MEMORY_DIR)/LSU.v
RTL_LSU_CONTROL := $(RTL_MEMORY_DIR)/LSUControl.v
RTL_LSU_DATAPATH := $(RTL_MEMORY_DIR)/LSUDataPath.v
RTL_PMP_CHECKER := $(RTL_MEMORY_DIR)/PmpChecker.v
RTL_TYPED_PMA_CHECKER := $(RTL_MEMORY_DIR)/OooTypedPmaChecker.v
RTL_PMA_CHECKER := $(RTL_MEMORY_DIR)/OooPmaChecker.v
RTL_OOO_TYPED_MEMORY_CLASSIFIER := $(RTL_MEMORY_DIR)/OooTypedMemoryClassifier.v
RTL_OOO_POST_TRANSLATE_MEMORY_CLASS := $(RTL_MEMORY_DIR)/OooPostTranslateMemoryClass.v
RTL_OOO_MEMORY_REQUEST_GATE := $(RTL_MEMORY_DIR)/OooMemoryRequestGate.v
RTL_OOO_STORE_QUEUE := $(RTL_MEMORY_DIR)/OooStoreQueue.v
RTL_OOO_LOAD_QUEUE := $(RTL_MEMORY_DIR)/OooLoadQueue.v
RTL_OOO_MEM_INFLIGHT_QUEUE := $(RTL_MEMORY_DIR)/OooMemInflightQueue.v
RTL_OOO_MMU_EPOCH_OWNER := $(RTL_MEMORY_DIR)/OooMmuEpochOwner.v
RTL_OOO_MEM_OWNER_TRACKER := $(RTL_MEMORY_DIR)/OooMemOwnerTracker.v
RTL_OOO_MEM_OWNER_TERMINAL_COLLECTOR := $(RTL_MEMORY_DIR)/OooMemOwnerTerminalCollector.v
# 子系统 wrapper：聚合 memory 访问相关组合/时序 owner，供 OooCoreTopGlue 单实例化。
RTL_OOO_MEMORY_ACCESS := $(RTL_MEMORY_DIR)/OooMemoryAccess.v


RTL_OOO_RENAME_MAP := $(RTL_RENAME_ALLOCATE_DIR)/OooRenameMap.v
RTL_OOO_FREE_LIST := $(RTL_RENAME_ALLOCATE_DIR)/OooFreeList.v
RTL_OOO_ROB := $(RTL_WRITEBACK_DIR)/OooRob.v
RTL_OOO_PHYS_REG_FILE := $(RTL_REGREAD_BYPASS_DIR)/OooPhysRegFile.v
RTL_OOO_FP_REG_FILE := $(RTL_REGREAD_BYPASS_DIR)/OooFpRegFile.v
RTL_OOO_PENDING_OPERAND_READ_GATE := $(RTL_REGREAD_BYPASS_DIR)/OooPendingOperandReadGate.v
RTL_OOO_BUSY_TABLE := $(RTL_RENAME_ALLOCATE_DIR)/OooBusyTable.v
RTL_OOO_INT_ISSUE_SELECT8 := $(RTL_SCHEDULING_DIR)/OooIntIssueSelect8.v
RTL_OOO_INT_ISSUE_QUEUE := $(RTL_OOO_INT_ISSUE_SELECT8) \
	$(RTL_SCHEDULING_DIR)/OooIntIssueQueue.v
RTL_OOO_FP_ISSUE_QUEUE := $(RTL_SCHEDULING_DIR)/OooFpIssueQueue.v
RTL_OOO_FP_PHYS_REG_FILE := $(RTL_REGREAD_BYPASS_DIR)/OooFpPhysRegFile.v
RTL_OOO_FP_BACKEND := $(RTL_EXECUTE_DIR)/OooFpBackend.v
RTL_OOO_DISPATCH_BACKEND := $(RTL_RENAME_ALLOCATE_DIR)/OooDispatchBackend.v
RTL_OOO_MULDIV_UNIT := $(RTL_EXECUTE_DIR)/OooMulDivUnit.v
RTL_OOO_CLMUL_UNIT := $(RTL_EXECUTE_DIR)/OooClmulUnit.v
RTL_OOO_INT_BACKEND := $(RTL_EXECUTE_DIR)/OooIntBackend.v
# 整数位操作（Zbb/Zbc/Zbs bitmanip 路径）纯组合 owner，从 OooIntBackend 抽出。
RTL_OOO_BITMANIP_GATE := $(RTL_EXECUTE_DIR)/OooBitmanipGate.v
# 原子访存结果（RV64A AMO）纯组合 owner，从 OooIntBackend 抽出。
RTL_OOO_AMO_GATE := $(RTL_EXECUTE_DIR)/OooAmoGate.v
RTL_OOO_ALU_DECODE_BACKEND := $(RTL_DECODE_DIR)/OooAluDecodeBackend.v
RTL_OOO_ARCH_REG_FILE := $(RTL_WRITEBACK_DIR)/OooArchRegFile.v
RTL_OOO_CONTROL_COMMIT_SEQUENCER := $(RTL_WRITEBACK_DIR)/OooControlCommitSequencer.v
RTL_OOO_COMMIT_OUTPUT_MUX := $(RTL_WRITEBACK_DIR)/OooCommitOutputMux.v
RTL_OOO_CONTROL_FLUSH_SEQUENCER := $(RTL_CONTROL_DIR)/OooControlFlushSequencer.v
RTL_OOO_CONTROL_EVENT_APPLY_SEQUENCER := $(RTL_CONTROL_DIR)/OooControlEventApplySequencer.v
# P4 复活（2026-07-08，pipeline-stage-boundary.md §5 flush 单点化）：统一 redirect 年龄律仲裁器。
# shadow 阶段由 OooCoreTopGlue 在 `ifdef OOO_ASSERT 下实例化作等价断言（经 RTL_OOO_FRONTEND_HELPERS
# 进 RTL_CORE_SRCS 与全部 glue 系 TB；综合无 OOO_ASSERT → 无实例 → hierarchy 剪除零面积）。
RTL_OOO_REDIRECT_ARBITER := $(RTL_CONTROL_DIR)/OooRedirectArbiter.v
# 子系统 wrapper：聚合 CSR/trap/pending/drain/flush/stop/observable 控制 owner，供 OooCoreTopGlue 单实例化。
RTL_OOO_CONTROL_PLANE := $(RTL_CONTROL_DIR)/OooControlPlane.v
RTL_OOO_STOP_PENDING_SEQUENCER := $(RTL_CONTROL_DIR)/OooStopPendingSequencer.v
RTL_OOO_CORE_OBSERVABLE_OUTPUT_GATE := $(RTL_CONTROL_DIR)/OooCoreObservableOutputGate.v
RTL_OOO_CORE_SLICE_CONTROL_GATE := $(RTL_CONTROL_DIR)/OooCoreSliceControlGate.v
RTL_OOO_CSR_ILLEGAL_PROBE_GATE := $(RTL_CONTROL_DIR)/OooCsrIllegalProbeGate.v
RTL_OOO_CSR_ACCESS_REQUEST_MUX := $(RTL_CONTROL_DIR)/OooCsrAccessRequestMux.v
RTL_OOO_CSR_TRAP_REQUEST_MUX := $(RTL_CONTROL_DIR)/OooCsrTrapRequestMux.v
RTL_OOO_PENDING_LANE1_CAPTURE_GATE := $(RTL_CONTROL_DIR)/OooPendingLane1CaptureGate.v
RTL_OOO_PENDING_DISPATCH_ARBITER := $(RTL_CONTROL_DIR)/OooPendingDispatchArbiter.v
RTL_OOO_PENDING_DRAIN_RESOLVE_GATE := $(RTL_CONTROL_DIR)/OooPendingDrainResolveGate.v
RTL_OOO_SERIALIZED_MEM_TERMINAL_PERMIT := $(RTL_CONTROL_DIR)/OooSerializedMemTerminalPermit.v
RTL_OOO_PENDING_SYSTEM_ADMISSION_CANCEL_GATE := $(RTL_CONTROL_DIR)/OooPendingSystemAdmissionCancelGate.v
RTL_OOO_PENDING_SYSTEM_SEQUENCER := $(RTL_CONTROL_DIR)/OooPendingSystemSequencer.v
RTL_OOO_PENDING_TRAP_EXIT_SEQUENCER := $(RTL_CONTROL_DIR)/OooPendingTrapExitSequencer.v
RTL_OOO_TRAP_EXIT_EVENT_MUX := $(RTL_CONTROL_DIR)/OooTrapExitEventMux.v
RTL_OOO_TRAP_EXIT_OUTPUT_SEQUENCER := $(RTL_CONTROL_DIR)/OooTrapExitOutputSequencer.v
# 子系统 wrapper：聚合 commit/retire/FP-commit owner，供 OooCoreTopGlue 单实例化。
RTL_OOO_WRITEBACK := $(RTL_WRITEBACK_DIR)/OooWriteback.v
RTL_OOO_ALU_CORE_SLICE := $(RTL_EXECUTE_DIR)/OooAluCoreSlice.v
# 子系统 wrapper：聚合整数 core slice、FP pending exec/sequencer、branch compare，供 OooCoreTopGlue 单实例化。
RTL_OOO_EXECUTE_BACKEND := $(RTL_EXECUTE_DIR)/OooExecuteBackend.v
RTL_OOO_RVC_DECOMPRESSOR := $(RTL_DECODE_DIR)/OooRvcDecompressor.v
RTL_OOO_FP_DECODE := $(RTL_DECODE_DIR)/OooFpDecode.v
RTL_OOO_FETCH_STATIC_CLASSIFY := $(RTL_FRONTEND_DIR)/OooFetchStaticClassify.v
RTL_OOO_FETCH_HEAD_CLASSIFY_GATE := $(RTL_FRONTEND_DIR)/OooFetchHeadClassifyGate.v
RTL_OOO_FETCH_HEAD_PAIR_GATE := $(RTL_FRONTEND_DIR)/OooFetchHeadPairGate.v
# FP 访存操作数形成（地址/对齐/store wdata/wstrb）纯组合 owner，从 FP 巨石抽出。
# FP 分类（FCLASS.S/D）纯组合 owner，从 FP 巨石抽出。
RTL_OOO_FP_CLASSIFY_GATE := $(RTL_EXECUTE_DIR)/OooFpClassifyGate.v
# FP 符号注入（FSGNJ/N/X）纯组合 owner，从 FP 巨石抽出。
RTL_OOO_FP_SGNJ_GATE := $(RTL_EXECUTE_DIR)/OooFpSgnjGate.v
# FP 比较/最值（FEQ/FLT/FLE、FMIN/FMAX）纯组合 owner，从 FP 巨石抽出。
RTL_OOO_FP_COMPARE_GATE := $(RTL_EXECUTE_DIR)/OooFpCompareGate.v
# FP 转换（FCVT int↔fp / fp↔fp）纯组合 owner，从 FP 巨石抽出。
RTL_OOO_FP_CONVERT_GATE := $(RTL_EXECUTE_DIR)/OooFpConvertGate.v
# FP short-arithmetic production children：固定拥有 AddSub S1-S3、Mul S1/S2-S3、
# FMA S1-S3/S4-S5 数值与 fflags Q；wrapper 只保留事务 meta/kill/对齐。
RTL_OOO_FP_ADD_SUB_PIPE := $(RTL_EXECUTE_DIR)/OooFpAddSubPipe.v
RTL_OOO_FP_MUL_PRODUCT_PIPE := $(RTL_EXECUTE_DIR)/OooFpMulProductPipe.v
RTL_OOO_FP_MUL_NORM_ROUND_PIPE := $(RTL_EXECUTE_DIR)/OooFpMulNormRoundPipe.v
RTL_OOO_FP_FMA_ALIGN_ADD_PIPE := $(RTL_EXECUTE_DIR)/OooFpFmaAlignAddPipe.v
RTL_OOO_FP_FMA_NORM_ROUND_PIPE := $(RTL_EXECUTE_DIR)/OooFpFmaNormRoundPipe.v
RTL_OOO_FP_ARITH_CHILDREN := \
	$(RTL_OOO_FP_ADD_SUB_PIPE) \
	$(RTL_OOO_FP_MUL_PRODUCT_PIPE) \
	$(RTL_OOO_FP_MUL_NORM_ROUND_PIPE) \
	$(RTL_OOO_FP_FMA_ALIGN_ADD_PIPE) \
	$(RTL_OOO_FP_FMA_NORM_ROUND_PIPE)
# FP 加减/乘/乘加（FADD/FSUB/FMUL/FMADD 系列）事务 wrapper。
RTL_OOO_FP_ARITH_GATE := $(RTL_EXECUTE_DIR)/OooFpArithGate.v
# FP 长延迟运算（FDIV/FSQRT，含迭代器）时序 owner，从 FP 巨石抽出。
RTL_OOO_FP_LONG_OP_GATE := $(RTL_EXECUTE_DIR)/OooFpLongOpGate.v
# FP execute 子系统共享谓词（NaN/sNaN/NaN-box/inf/zero）头文件。
RTL_OOO_FP_PREDICATES_V := $(RTL_EXECUTE_DIR)/OooFpPredicates.v
# FP execute 子系统共享舍入/规格化 helper（lzc/norm/shift-jam/round）头文件。
RTL_OOO_FP_ROUND_V := $(RTL_EXECUTE_DIR)/OooFpRound.v
RTL_OOO_RAS_STACK := $(RTL_FRONTEND_DIR)/OooRasStack.v
RTL_OOO_DIRECT_RAS_CANDIDATE_GATE := $(RTL_FRONTEND_DIR)/OooDirectRasCandidateGate.v
RTL_OOO_DIRECT_CONTROL_FLOW_GATE := $(RTL_FRONTEND_DIR)/OooDirectControlFlowGate.v
RTL_OOO_RAS_UPDATE_GATE := $(RTL_FRONTEND_DIR)/OooRasUpdateGate.v
RTL_OOO_BRANCH_SPEC_TRACKER := $(RTL_FRONTEND_DIR)/OooBranchSpecTracker.v
RTL_OOO_FETCH_PC_OUTSTANDING_SEQUENCER := $(RTL_FRONTEND_DIR)/OooFetchPcOutstandingSequencer.v
RTL_OOO_FRONTEND_UOP_SAFETY := $(RTL_FRONTEND_DIR)/OooFrontendUopSafety.v
RTL_OOO_FRONTEND_DISPATCH_GATE := $(RTL_FRONTEND_DIR)/OooFrontendDispatchGate.v
RTL_OOO_FRONTEND_BACKEND_DISPATCH_MUX := $(RTL_FRONTEND_DIR)/OooFrontendBackendDispatchMux.v
RTL_OOO_DIRECT_BRANCH_RESOLVE_GATE := $(RTL_FRONTEND_DIR)/OooDirectBranchResolveGate.v
RTL_OOO_BRANCH_RESOLVE_RECOVERY_GATE := $(RTL_FRONTEND_DIR)/OooBranchResolveRecoveryGate.v
# [wave5b 死硅拆除] RTL_OOO_PENDING_CONTROL_RESOLVE_GATE / _BRANCH_SEQUENCER / _JUMP_SEQUENCER 已删
RTL_OOO_BRANCH_APPEND_DISPATCH_GATE := $(RTL_FRONTEND_DIR)/OooBranchAppendDispatchGate.v
RTL_OOO_BRANCH_BPU_UPDATE_GATE := $(RTL_FRONTEND_DIR)/OooBranchBpuUpdateGate.v
RTL_OOO_BRANCH_LOCAL_PHT := $(RTL_FRONTEND_DIR)/OooBranchLocalPht.v
RTL_OOO_FRONTEND_RUN_GATE := $(RTL_FRONTEND_DIR)/OooFrontendRunGate.v
# 子系统 wrapper：聚合取指/分支预测/BPU/RAS/BTB/prefetch/FIFO/pending control 等前端 owner，供 OooCoreTopGlue 单实例化。
RTL_OOO_FRONTEND := $(RTL_FRONTEND_DIR)/OooFrontend.v
RTL_OOO_FRONTEND_ACTION_GATE := $(RTL_FRONTEND_DIR)/OooFrontendActionGate.v
RTL_OOO_FETCH_REQUEST_MUX := $(RTL_FRONTEND_DIR)/OooFetchRequestMux.v
RTL_OOO_DIRECT_BRANCH_WAIT_BUFFER := $(RTL_FRONTEND_DIR)/OooDirectBranchWaitBuffer.v
RTL_OOO_BACKEND_DRAIN_TRACKER := $(RTL_FRONTEND_DIR)/OooBackendDrainTracker.v
RTL_OOO_FETCH_PACKET_HEAD_MUX := $(RTL_FRONTEND_DIR)/OooFetchPacketHeadMux.v
RTL_OOO_FETCH_PACKET_SEED_MUX := $(RTL_FRONTEND_DIR)/OooFetchPacketSeedMux.v
RTL_OOO_FETCH_BRANCH_TARGET := $(RTL_FRONTEND_DIR)/OooFetchBranchTarget.v
RTL_OOO_FETCH_PACKET_DECODE := $(RTL_FRONTEND_DIR)/OooFetchPacketDecode.v
RTL_OOO_FETCH_PACKET_FIFO := $(RTL_FRONTEND_DIR)/OooFetchPacketFifo.v
RTL_OOO_FETCH_FLOW_CONTROL := $(RTL_FRONTEND_DIR)/OooFetchFlowControl.v
RTL_OOO_FP_DIV_ITER := $(RTL_EXECUTE_DIR)/OooFpDivIter.v
RTL_OOO_FP_SQRT_ITER := $(RTL_EXECUTE_DIR)/OooFpSqrtIter.v
RTL_OOO_FRONTEND_HELPERS := $(RTL_OOO_RVC_DECOMPRESSOR) $(RTL_OOO_FP_DECODE) \
	$(RTL_OOO_FETCH_STATIC_CLASSIFY) \
	$(RTL_OOO_FETCH_HEAD_CLASSIFY_GATE) \
	$(RTL_OOO_FETCH_HEAD_PAIR_GATE) \
	$(RTL_OOO_FP_CLASSIFY_GATE) \
	$(RTL_OOO_FP_SGNJ_GATE) \
	$(RTL_OOO_FP_COMPARE_GATE) \
	$(RTL_OOO_FP_CONVERT_GATE) \
	$(RTL_OOO_FP_ARITH_CHILDREN) \
	$(RTL_OOO_FP_ARITH_GATE) \
	$(RTL_OOO_FP_LONG_OP_GATE) \
	$(RTL_OOO_FP_REG_FILE) \
	$(RTL_OOO_PENDING_OPERAND_READ_GATE) \
	$(RTL_OOO_RAS_STACK) \
	$(RTL_OOO_DIRECT_RAS_CANDIDATE_GATE) \
	$(RTL_OOO_DIRECT_CONTROL_FLOW_GATE) \
	$(RTL_OOO_RAS_UPDATE_GATE) \
	$(RTL_OOO_BRANCH_SPEC_TRACKER) \
	$(RTL_OOO_FETCH_PC_OUTSTANDING_SEQUENCER) \
	$(RTL_OOO_CONTROL_COMMIT_SEQUENCER) \
	$(RTL_OOO_COMMIT_OUTPUT_MUX) \
	$(RTL_OOO_CONTROL_FLUSH_SEQUENCER) \
	$(RTL_OOO_CONTROL_EVENT_APPLY_SEQUENCER) \
	$(RTL_OOO_REDIRECT_ARBITER) \
	$(RTL_OOO_STOP_PENDING_SEQUENCER) \
	$(RTL_OOO_CORE_OBSERVABLE_OUTPUT_GATE) \
	$(RTL_OOO_CORE_SLICE_CONTROL_GATE) \
	$(RTL_OOO_CSR_ILLEGAL_PROBE_GATE) \
	$(RTL_OOO_CSR_ACCESS_REQUEST_MUX) \
	$(RTL_OOO_CSR_TRAP_REQUEST_MUX) \
	$(RTL_OOO_PENDING_LANE1_CAPTURE_GATE) \
	$(RTL_OOO_PENDING_DISPATCH_ARBITER) \
	$(RTL_OOO_PENDING_DRAIN_RESOLVE_GATE) \
	$(RTL_OOO_SERIALIZED_MEM_TERMINAL_PERMIT) \
	$(RTL_OOO_PENDING_SYSTEM_ADMISSION_CANCEL_GATE) \
	$(RTL_OOO_PENDING_SYSTEM_SEQUENCER) \
	$(RTL_OOO_PENDING_TRAP_EXIT_SEQUENCER) \
	$(RTL_OOO_TRAP_EXIT_EVENT_MUX) \
	$(RTL_OOO_TRAP_EXIT_OUTPUT_SEQUENCER) \
	$(RTL_OOO_WRITEBACK) \
	$(RTL_OOO_EXECUTE_BACKEND) \
	$(RTL_OOO_CONTROL_PLANE) \
	$(RTL_OOO_FRONTEND) \
	$(RTL_OOO_MEMORY_REQUEST_GATE) \
	$(RTL_OOO_MEMORY_ACCESS) \
	$(RTL_OOO_FRONTEND_UOP_SAFETY) \
	$(RTL_OOO_FRONTEND_DISPATCH_GATE) \
	$(RTL_OOO_FRONTEND_BACKEND_DISPATCH_MUX) \
	$(RTL_OOO_DIRECT_BRANCH_RESOLVE_GATE) \
	$(RTL_OOO_BRANCH_RESOLVE_RECOVERY_GATE) \
	$(RTL_OOO_BRANCH_APPEND_DISPATCH_GATE) \
	$(RTL_OOO_BRANCH_BPU_UPDATE_GATE) \
	$(RTL_OOO_BRANCH_LOCAL_PHT) \
	$(RTL_OOO_FRONTEND_RUN_GATE) \
	$(RTL_OOO_FRONTEND_ACTION_GATE) \
	$(RTL_OOO_FETCH_REQUEST_MUX) \
	$(RTL_OOO_DIRECT_BRANCH_WAIT_BUFFER) \
	$(RTL_OOO_BACKEND_DRAIN_TRACKER) \
	$(RTL_OOO_FETCH_PACKET_HEAD_MUX) \
	$(RTL_OOO_FETCH_PACKET_SEED_MUX) \
	$(RTL_OOO_FETCH_BRANCH_TARGET) \
	$(RTL_OOO_FETCH_PACKET_DECODE) \
	$(RTL_OOO_FETCH_PACKET_FIFO) \
	$(RTL_OOO_FETCH_FLOW_CONTROL) \
	$(RTL_OOO_FP_DIV_ITER) \
	$(RTL_OOO_FP_SQRT_ITER) \
	$(RTL_OOO_BRANCH_DIRECTION_PREDICTOR)
RTL_OOO_CORE_TOP_GLUE := $(RTL_CORE_DIR)/OooCoreTopGlue.v

RTL_NPC_AXI_BUS := $(RTL_BUS_DIR)/NpcAxiBus.v
# 兼容历史 mutation runner 的 RTL_AXI_XBAR=... 覆盖；生产清单只暴露当前全称。
RTL_AXI_CROSSBAR := $(if $(RTL_AXI_XBAR),$(RTL_AXI_XBAR),$(RTL_BUS_DIR)/AxiCrossbar.v)
RTL_AXI_DEFAULT_SLAVE := $(RTL_BUS_DIR)/AxiDefaultSlave.v
RTL_AXI_RESET_SYSCON := $(RTL_BUS_DIR)/AxiResetSyscon.v
RTL_AXI_CLINT := $(RTL_BUS_DIR)/AxiClint.v
RTL_AXI_PLIC := $(RTL_BUS_DIR)/AxiPlic.v
RTL_UART := $(RTL_BUS_DIR)/Uart.v
RTL_AXI_TO_UART := $(RTL_BUS_DIR)/AxiToUart.v


RTL_WBU := $(RTL_WRITEBACK_DIR)/WBU.v

RTL_AXI_DPI_SLAVE := $(RTL_SIM_DIR)/AxiDpiSlave.sv
RTL_AXI_VIRTIO_BLK := $(RTL_SIM_DIR)/AxiVirtioBlk.sv
RTL_NPC_SIM_TOP := $(RTL_SIM_DIR)/NpcSimTop.sv
# §5 三层观测模型 ② 层 checker(旁挂 SIM_TOP, 不进 RTL_CORE_SRCS → DCE 零面积)
RTL_OOO_REDIRECT_MUX_CHECKER := $(RTL_DEBUG_DIR)/OooRedirectMuxChecker.sv
RTL_OOO_REDIRECT_SEQ_CHECKER := $(RTL_DEBUG_DIR)/OooRedirectSeqChecker.sv
# 【P4 切消费点(2026-07-09)】OooRedirectMergeChecker(跨 Mux/Seq untracked 一致性 INV-M1)退役:
# 两汇合点消费同一 OooRedirectArbiter 赢家 → 跨器一致性由单源构造保证, 对照物不复存在。
RTL_OOO_AD_UPDATE_CHECKER := $(RTL_DEBUG_DIR)/OooAdUpdateChecker.sv
RTL_OOO_BRANCH_DIRECTION_PREDICTOR_CHECKER := $(RTL_DEBUG_DIR)/OooBranchDirectionPredictorChecker.sv
RTL_OOO_FETCH_PACKET_CACHE_CHECKER := $(RTL_DEBUG_DIR)/OooFetchPacketCacheChecker.sv
RTL_OOO_DATA_WORD_CACHE_CHECKER := $(RTL_DEBUG_DIR)/OooDataWordCacheChecker.sv

RTL_HEADER_SRCS := $(RTL_DEFINE) $(RTL_OOO_SLOT_FACTS_V) $(RTL_OOO_FP_PREDICATES_V) \
	$(RTL_OOO_FP_ROUND_V)
RTL_CORE_SRCS := $(strip \
	$(RTL_ALU) \
		$(RTL_AXI_DEFAULT_SLAVE) \
		$(RTL_AXI_RESET_SYSCON) \
		$(RTL_AXI_CLINT) \
		$(RTL_AXI_PLIC) \
		$(RTL_AXI_CROSSBAR) \
	$(RTL_UART) \
	$(RTL_AXI_TO_UART) \
	$(RTL_COMPARE_UNIT) \
	$(RTL_DECODE_STAGE) \
	$(RTL_DECODE_UNIT) \
	$(RTL_IMM_GEN) \
	$(RTL_LSU_CONTROL) \
	$(RTL_LSU_DATAPATH) \
	$(RTL_LSU) \
	$(RTL_CSR_FILE) \
	$(RTL_NPC_AXI_BUS) \
	$(RTL_PMP_CHECKER) \
	$(RTL_TYPED_PMA_CHECKER) \
	$(RTL_PMA_CHECKER) \
	$(RTL_OOO_TYPED_MEMORY_CLASSIFIER) \
	$(RTL_OOO_POST_TRANSLATE_MEMORY_CLASS) \
	$(RTL_OOO_SV39_TLB) \
	$(RTL_OOO_FETCH_PACKET_CACHE) \
	$(RTL_OOO_DATA_WORD_CACHE) \
	$(RTL_SRAM_FETCH_PACKET) \
	$(RTL_SRAM_DATA_WORD) \
	$(RTL_PIPE_STAGE_REG) \
	$(RTL_NPC_CORE_TOP) \
	$(RTL_NPC_TOP) \
	$(RTL_OOO_FETCH_AXI_BRIDGE) \
	$(RTL_OOO_MEM_AXI_BRIDGE) \
	$(RTL_OOO_LSU_AXI_LANE_ADAPTER) \
	$(RTL_OOO_DUAL_MEM_AXI_ARBITER) \
	$(RTL_OOO_DUAL_MEM_BRIDGE_WRAPPER) \
	$(RTL_OOO_FRONTEND_HELPERS) \
	$(RTL_OOO_CORE_TOP_GLUE) \
	$(RTL_OOO_ALU_CORE_SLICE) \
	$(RTL_OOO_ALU_DECODE_BACKEND) \
	$(RTL_OOO_ARCH_REG_FILE) \
	$(RTL_OOO_BUSY_TABLE) \
	$(RTL_OOO_DISPATCH_BACKEND) \
	$(RTL_OOO_FREE_LIST) \
	$(RTL_OOO_MULDIV_UNIT) \
	$(RTL_OOO_CLMUL_UNIT) \
	$(RTL_OOO_INT_BACKEND) \
	$(RTL_OOO_STORE_QUEUE) \
	$(RTL_OOO_LOAD_QUEUE) \
	$(RTL_OOO_MEM_INFLIGHT_QUEUE) \
	$(RTL_OOO_MMU_EPOCH_OWNER) \
	$(RTL_OOO_MEM_OWNER_TRACKER) \
	$(RTL_OOO_MEM_OWNER_TERMINAL_COLLECTOR) \
	$(RTL_OOO_BITMANIP_GATE) \
	$(RTL_OOO_AMO_GATE) \
	$(RTL_OOO_INT_ISSUE_QUEUE) \
	$(RTL_OOO_FP_ISSUE_QUEUE) \
	$(RTL_OOO_FP_PHYS_REG_FILE) \
	$(RTL_OOO_FP_BACKEND) \
	$(RTL_OOO_PHYS_REG_FILE) \
	$(RTL_OOO_RENAME_MAP) \
	$(RTL_OOO_ROB) \
	$(RTL_WBU))
SIM_TOP_SRCS := $(RTL_AXI_DPI_SLAVE) $(RTL_AXI_VIRTIO_BLK) $(RTL_NPC_SIM_TOP) \
	$(RTL_OOO_REDIRECT_MUX_CHECKER) \
	$(RTL_OOO_REDIRECT_SEQ_CHECKER) \
	$(RTL_OOO_AD_UPDATE_CHECKER)
VSRCS = $(RTL_CORE_SRCS) $(SIM_TOP_SRCS)
