// Native CPU/platform with the real Tensor NPU and shared physical-memory DMA.
// Serial retirement waits for all DMA responses and cache invalidation.
module R64TensorSystemTop(
 input clk_i,
 input rst_i,
 input run_i,
 input [1:0] trace_ready_i,
 output [1:0] trace_valid_o,
 output [127:0] trace_pc_o,
 output [127:0] trace_raw_o,
 output [127:0] trace_npc_o,
 output [127:0] trace_data_o,
 output [7:0] trace_length_o,
 output [1:0] trace_rd_write_o,
 output [1:0] trace_rd_fp_o,
 output [9:0] trace_rd_arch_o,
 output [9:0] trace_fflags_o,
 output [15:0] trace_kind_o,
 output trap_valid_o,
 output trap_interrupt_o,
 output [5:0] trap_cause_o,
 output [63:0] trap_pc_o,
 output [63:0] trap_tval_o,
 output [63:0] trap_raw_o,
 output [63:0] trap_target_o,
 output [3:0] trap_length_o,
 output [1:0] privilege_o,
 output [63:0] mstatus_o,
 output [63:0] satp_o,
 output [5:0] rob_count_o,
 output [3:0] ext_arvalid_o,
 input [3:0] ext_arready_i,
 output [255:0] ext_araddr_o,
 output [11:0] ext_arsize_o,
 output [11:0] ext_arprot_o,
 input [3:0] ext_rvalid_i,
 output [3:0] ext_rready_o,
 input [255:0] ext_rdata_i,
 input [7:0] ext_rresp_i,
 output [3:0] ext_awvalid_o,
 input [3:0] ext_awready_i,
 output [255:0] ext_awaddr_o,
 output [11:0] ext_awsize_o,
 output [3:0] ext_wvalid_o,
 input [3:0] ext_wready_i,
 output [255:0] ext_wdata_o,
 output [31:0] ext_wstrb_o,
 input [3:0] ext_bvalid_i,
 output [3:0] ext_bready_o,
 input [7:0] ext_bresp_i,
 input uart_rx_valid_i,
 input [7:0] uart_rx_data_i,
 output uart_rx_ready_o,
 output uart_tx_valid_o,
 output [7:0] uart_tx_data_o,
 input [31:0] external_irq_sources_i,
 output syscon_valid_o,
 output [31:0] syscon_value_o,
 output [63:0] time_o,
 output protocol_error_o,
 output gmem_req_valid_o,
 input gmem_req_ready_i,
 output gmem_req_write_o,
 output [63:0] gmem_req_addr_o,
 output [63:0] gmem_req_wdata_o,
 output [7:0] gmem_req_wstrb_o,
 output [8:0] gmem_req_tag_o,
 input gmem_rsp_valid_i,
 output gmem_rsp_ready_o,
 input [63:0] gmem_rsp_rdata_i,
 input gmem_rsp_error_i,
 input [8:0] gmem_rsp_tag_i
);
 wire dma_invalidate_i;
 wire tensor_cmd_valid_o;
 wire tensor_cmd_ready_i;
 wire [8:0] tensor_cmd_tag_o;
 wire [63:0] tensor_cmd_o;
 wire [63:0] tensor_operand_o;
 wire tensor_pair_o;
 wire [7:0] tensor_class_o;
 wire tensor_terminal_valid_i;
 wire tensor_terminal_ready_o;
 wire [8:0] tensor_terminal_tag_i;
 wire tensor_error_i;
 wire [7:0] tensor_error_code_i;
 wire system_error,tensor_protocol_error;
 assign protocol_error_o=system_error|tensor_protocol_error;
 R64SystemTop system(
  .clk_i(clk_i),
  .rst_i(rst_i),
  .run_i(run_i),
  .dma_invalidate_i(dma_invalidate_i),
  .tensor_cmd_valid_o(tensor_cmd_valid_o),
  .tensor_cmd_ready_i(tensor_cmd_ready_i),
  .tensor_cmd_tag_o(tensor_cmd_tag_o),
  .tensor_cmd_o(tensor_cmd_o),
  .tensor_operand_o(tensor_operand_o),
  .tensor_pair_o(tensor_pair_o),
  .tensor_class_o(tensor_class_o),
  .tensor_terminal_valid_i(tensor_terminal_valid_i),
  .tensor_terminal_ready_o(tensor_terminal_ready_o),
  .tensor_terminal_tag_i(tensor_terminal_tag_i),
  .tensor_error_i(tensor_error_i),
  .tensor_error_code_i(tensor_error_code_i),
  .trace_ready_i(trace_ready_i),
  .trace_valid_o(trace_valid_o),
  .trace_pc_o(trace_pc_o),
  .trace_raw_o(trace_raw_o),
  .trace_npc_o(trace_npc_o),
  .trace_data_o(trace_data_o),
  .trace_length_o(trace_length_o),
  .trace_rd_write_o(trace_rd_write_o),
  .trace_rd_fp_o(trace_rd_fp_o),
  .trace_rd_arch_o(trace_rd_arch_o),
  .trace_fflags_o(trace_fflags_o),
  .trace_kind_o(trace_kind_o),
  .trap_valid_o(trap_valid_o),
  .trap_interrupt_o(trap_interrupt_o),
  .trap_cause_o(trap_cause_o),
  .trap_pc_o(trap_pc_o),
  .trap_tval_o(trap_tval_o),
  .trap_raw_o(trap_raw_o),
  .trap_target_o(trap_target_o),
  .trap_length_o(trap_length_o),
  .privilege_o(privilege_o),
  .mstatus_o(mstatus_o),
  .satp_o(satp_o),
  .rob_count_o(rob_count_o),
  .ext_arvalid_o(ext_arvalid_o),
  .ext_arready_i(ext_arready_i),
  .ext_araddr_o(ext_araddr_o),
  .ext_arsize_o(ext_arsize_o),
  .ext_arprot_o(ext_arprot_o),
  .ext_rvalid_i(ext_rvalid_i),
  .ext_rready_o(ext_rready_o),
  .ext_rdata_i(ext_rdata_i),
  .ext_rresp_i(ext_rresp_i),
  .ext_awvalid_o(ext_awvalid_o),
  .ext_awready_i(ext_awready_i),
  .ext_awaddr_o(ext_awaddr_o),
  .ext_awsize_o(ext_awsize_o),
  .ext_wvalid_o(ext_wvalid_o),
  .ext_wready_i(ext_wready_i),
  .ext_wdata_o(ext_wdata_o),
  .ext_wstrb_o(ext_wstrb_o),
  .ext_bvalid_i(ext_bvalid_i),
  .ext_bready_o(ext_bready_o),
  .ext_bresp_i(ext_bresp_i),
  .uart_rx_valid_i(uart_rx_valid_i),
  .uart_rx_data_i(uart_rx_data_i),
  .uart_rx_ready_o(uart_rx_ready_o),
  .uart_tx_valid_o(uart_tx_valid_o),
  .uart_tx_data_o(uart_tx_data_o),
  .external_irq_sources_i(external_irq_sources_i),
  .syscon_valid_o(syscon_valid_o),
  .syscon_value_o(syscon_value_o),
  .time_o(time_o),
  .protocol_error_o(system_error)
 );
 R64TensorLink tensor(
  .clk_i(clk_i),.rst_i(rst_i),.cmd_valid_i(tensor_cmd_valid_o),.cmd_ready_o(tensor_cmd_ready_i),
  .cmd_tag_i(tensor_cmd_tag_o),.cmd_i(tensor_cmd_o),.operand_i(tensor_operand_o),
  .pair_i(tensor_pair_o),.class_i(tensor_class_o),
  .terminal_valid_o(tensor_terminal_valid_i),.terminal_ready_i(tensor_terminal_ready_o),
  .terminal_tag_o(tensor_terminal_tag_i),.error_o(tensor_error_i),.error_code_o(tensor_error_code_i),
  .dma_invalidate_o(dma_invalidate_i),.busy_o(),.protocol_error_o(tensor_protocol_error),
  .req_valid_o(gmem_req_valid_o),.req_ready_i(gmem_req_ready_i),.req_write_o(gmem_req_write_o),
  .req_addr_o(gmem_req_addr_o),.req_wdata_o(gmem_req_wdata_o),.req_wstrb_o(gmem_req_wstrb_o),
  .req_tag_o(gmem_req_tag_o),.rsp_valid_i(gmem_rsp_valid_i),.rsp_ready_o(gmem_rsp_ready_o),
  .rsp_rdata_i(gmem_rsp_rdata_i),.rsp_error_i(gmem_rsp_error_i),.rsp_tag_i(gmem_rsp_tag_i),
  .npu_error_o(),.npu_error_code_o(),.command_count_o(),.completion_count_o(),.macro_command_count_o(),
  .descriptor_resident_o(),.descriptor_expected_o()
 );
endmodule
