// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Symbol table internal header
//
// Internal details; most calling programs do not need this header,
// unless using verilator public meta comments.

#ifndef VERILATED_VNPCSIMTOP__SYMS_H_
#define VERILATED_VNPCSIMTOP__SYMS_H_  // guard

#include "verilated.h"

// INCLUDE MODEL CLASS

#include "VNpcSimTop.h"

// INCLUDE MODULE CLASSES
#include "VNpcSimTop___024root.h"
#include "VNpcSimTop___024unit.h"

// DPI TYPES for DPI Export callbacks (Internal use)

// SYMS CLASS (contains all model state)
class alignas(VL_CACHE_LINE_BYTES)VNpcSimTop__Syms final : public VerilatedSyms {
  public:
    // INTERNAL STATE
    VNpcSimTop* const __Vm_modelp;
    VlDeleter __Vm_deleter;
    bool __Vm_didInit = false;

    // MODULE INSTANCE STATE
    VNpcSimTop___024root           TOP;
    VNpcSimTop___024unit           TOP____024unit;

    // SCOPE NAMES
    VerilatedScope __Vscope_NpcSimTop;
    VerilatedScope __Vscope_NpcSimTop__u_ooo_fetch_adupd_checker;
    VerilatedScope __Vscope_NpcSimTop__u_ooo_fetch_adupd_checker__g_fetch_no_d;
    VerilatedScope __Vscope_NpcSimTop__u_ooo_mem0_adupd_checker;
    VerilatedScope __Vscope_NpcSimTop__u_ooo_mem1_adupd_checker;
    VerilatedScope __Vscope_NpcSimTop__u_ooo_rdmux_checker;
    VerilatedScope __Vscope_NpcSimTop__u_ooo_rdseq_checker;
    VerilatedScope __Vscope_NpcSimTop__u_top__u_core;
    VerilatedScope __Vscope_NpcSimTop__u_top__u_core__u_csr_file;
    VerilatedScope __Vscope_NpcSimTop__u_top__u_core__u_lsu_lane_adapter;
    VerilatedScope __Vscope_NpcSimTop__u_top__u_core__u_ooo_core;
    VerilatedScope __Vscope_NpcSimTop__u_top__u_core__u_ooo_core__u_control_event_apply_sequencer;
    VerilatedScope __Vscope_NpcSimTop__u_top__u_core__u_ooo_core__u_control_plane;
    VerilatedScope __Vscope_NpcSimTop__u_top__u_core__u_ooo_core__u_control_plane__u_pending_system_sequencer;
    VerilatedScope __Vscope_NpcSimTop__u_top__u_core__u_ooo_core__u_control_plane__u_pending_trap_exit_sequencer;
    VerilatedScope __Vscope_NpcSimTop__u_top__u_core__u_ooo_core__u_control_plane__u_stop_pending_sequencer;
    VerilatedScope __Vscope_NpcSimTop__u_top__u_core__u_ooo_core__u_execute_backend__u_core_slice;
    VerilatedScope __Vscope_NpcSimTop__u_top__u_core__u_ooo_core__u_execute_backend__u_core_slice__u_decode_backend__u_int_backend;
    VerilatedScope __Vscope_NpcSimTop__u_top__u_core__u_ooo_core__u_execute_backend__u_core_slice__u_decode_backend__u_int_backend__u_branch_resolve_stage;
    VerilatedScope __Vscope_NpcSimTop__u_top__u_core__u_ooo_core__u_execute_backend__u_core_slice__u_decode_backend__u_int_backend__u_clmul_unit;
    VerilatedScope __Vscope_NpcSimTop__u_top__u_core__u_ooo_core__u_execute_backend__u_core_slice__u_decode_backend__u_int_backend__u_dispatch_backend;
    VerilatedScope __Vscope_NpcSimTop__u_top__u_core__u_ooo_core__u_execute_backend__u_core_slice__u_decode_backend__u_int_backend__u_dispatch_backend__u_issue_queue;
    VerilatedScope __Vscope_NpcSimTop__u_top__u_core__u_ooo_core__u_execute_backend__u_core_slice__u_decode_backend__u_int_backend__u_dispatch_backend__u_rob;
    VerilatedScope __Vscope_NpcSimTop__u_top__u_core__u_ooo_core__u_execute_backend__u_core_slice__u_decode_backend__u_int_backend__u_ex0_stage;
    VerilatedScope __Vscope_NpcSimTop__u_top__u_core__u_ooo_core__u_execute_backend__u_core_slice__u_decode_backend__u_int_backend__u_ex1_stage;
    VerilatedScope __Vscope_NpcSimTop__u_top__u_core__u_ooo_core__u_execute_backend__u_core_slice__u_decode_backend__u_int_backend__u_fp_backend;
    VerilatedScope __Vscope_NpcSimTop__u_top__u_core__u_ooo_core__u_execute_backend__u_core_slice__u_decode_backend__u_int_backend__u_fp_backend__u_exec1_stage;
    VerilatedScope __Vscope_NpcSimTop__u_top__u_core__u_ooo_core__u_execute_backend__u_core_slice__u_decode_backend__u_int_backend__u_fp_backend__u_fp_arith;
    VerilatedScope __Vscope_NpcSimTop__u_top__u_core__u_ooo_core__u_execute_backend__u_core_slice__u_decode_backend__u_int_backend__u_fp_backend__u_fp_arith__fp_arith_pid_assert_blk;
    VerilatedScope __Vscope_NpcSimTop__u_top__u_core__u_ooo_core__u_execute_backend__u_core_slice__u_decode_backend__u_int_backend__u_fp_backend__u_fp_issue_queue;
    VerilatedScope __Vscope_NpcSimTop__u_top__u_core__u_ooo_core__u_execute_backend__u_core_slice__u_decode_backend__u_int_backend__u_fp_backend__u_fp_issue_queue__fp_iq_pid_unique_assert_blk;
    VerilatedScope __Vscope_NpcSimTop__u_top__u_core__u_ooo_core__u_execute_backend__u_core_slice__u_decode_backend__u_int_backend__u_fp_backend__u_fp_issue_stage;
    VerilatedScope __Vscope_NpcSimTop__u_top__u_core__u_ooo_core__u_execute_backend__u_core_slice__u_decode_backend__u_int_backend__u_fp_backend__u_fp_phys_reg_file;
    VerilatedScope __Vscope_NpcSimTop__u_top__u_core__u_ooo_core__u_execute_backend__u_core_slice__u_decode_backend__u_int_backend__u_fp_backend__v8i_fp_lease_assert_blk;
    VerilatedScope __Vscope_NpcSimTop__u_top__u_core__u_ooo_core__u_execute_backend__u_core_slice__u_decode_backend__u_int_backend__u_load_queue;
    VerilatedScope __Vscope_NpcSimTop__u_top__u_core__u_ooo_core__u_execute_backend__u_core_slice__u_decode_backend__u_int_backend__u_mem1_inflight_queue;
    VerilatedScope __Vscope_NpcSimTop__u_top__u_core__u_ooo_core__u_execute_backend__u_core_slice__u_decode_backend__u_int_backend__u_mem_inflight_queue;
    VerilatedScope __Vscope_NpcSimTop__u_top__u_core__u_ooo_core__u_execute_backend__u_core_slice__u_decode_backend__u_int_backend__u_mem_owner_terminal_collector;
    VerilatedScope __Vscope_NpcSimTop__u_top__u_core__u_ooo_core__u_execute_backend__u_core_slice__u_decode_backend__u_int_backend__u_mem_owner_tracker;
    VerilatedScope __Vscope_NpcSimTop__u_top__u_core__u_ooo_core__u_execute_backend__u_core_slice__u_decode_backend__u_int_backend__u_muldiv_unit;
    VerilatedScope __Vscope_NpcSimTop__u_top__u_core__u_ooo_core__u_execute_backend__u_core_slice__u_decode_backend__u_int_backend__u_phys_reg_file;
    VerilatedScope __Vscope_NpcSimTop__u_top__u_core__u_ooo_core__u_execute_backend__u_core_slice__u_decode_backend__u_int_backend__u_store_queue;
    VerilatedScope __Vscope_NpcSimTop__u_top__u_core__u_ooo_core__u_frontend;
    VerilatedScope __Vscope_NpcSimTop__u_top__u_core__u_ooo_core__u_frontend__u_fetch_dec0_branch_target;
    VerilatedScope __Vscope_NpcSimTop__u_top__u_core__u_ooo_core__u_frontend__u_fetch_dec1_branch_target;
    VerilatedScope __Vscope_NpcSimTop__u_top__u_core__u_ooo_core__u_frontend__u_fetch_packet_fifo;
    VerilatedScope __Vscope_NpcSimTop__u_top__u_core__u_ooo_core__u_frontend__u_redirect_arbiter;
    VerilatedScope __Vscope_NpcSimTop__u_top__u_core__u_ooo_core__u_writeback;
    VerilatedScope __Vscope_NpcSimTop__u_top__u_core__u_ooo_dual_mem_bridge;
    VerilatedScope __Vscope_NpcSimTop__u_top__u_core__u_ooo_dual_mem_bridge__u_bridge0;
    VerilatedScope __Vscope_NpcSimTop__u_top__u_core__u_ooo_dual_mem_bridge__u_bridge0__u_dcache;
    VerilatedScope __Vscope_NpcSimTop__u_top__u_core__u_ooo_dual_mem_bridge__u_bridge0__u_req_post_translate_class;
    VerilatedScope __Vscope_NpcSimTop__u_top__u_core__u_ooo_dual_mem_bridge__u_bridge0__u_walk_post_translate_class;
    VerilatedScope __Vscope_NpcSimTop__u_top__u_core__u_ooo_dual_mem_bridge__u_bridge1;
    VerilatedScope __Vscope_NpcSimTop__u_top__u_core__u_ooo_dual_mem_bridge__u_bridge1__u_dcache;
    VerilatedScope __Vscope_NpcSimTop__u_top__u_core__u_ooo_dual_mem_bridge__u_bridge1__u_req_post_translate_class;
    VerilatedScope __Vscope_NpcSimTop__u_top__u_core__u_ooo_dual_mem_bridge__u_bridge1__u_walk_post_translate_class;
    VerilatedScope __Vscope_NpcSimTop__u_top__u_core__u_ooo_dual_mem_bridge__u_miss_arbiter;
    VerilatedScope __Vscope_NpcSimTop__u_top__u_core__u_ooo_fetch_bridge;
    VerilatedScope __Vscope_NpcSimTop__u_top__u_core__u_ooo_fetch_bridge__u_fetch_packet_cache;
    VerilatedScope __Vscope_NpcSimTop__u_virtio_blk_axi;

    // CONSTRUCTORS
    VNpcSimTop__Syms(VerilatedContext* contextp, const char* namep, VNpcSimTop* modelp);
    ~VNpcSimTop__Syms();

    // METHODS
    const char* name() { return TOP.name(); }
};

#endif  // guard
