/***************************************************************************************
* Copyright (c) 2014-2024 Zihao Yu, Nanjing University
*
* NEMU is licensed under Mulan PSL v2.
* You can use this software according to the terms and conditions of the Mulan PSL v2.
* You may obtain a copy of Mulan PSL v2 at:
*          http://license.coscl.org.cn/MulanPSL2
*
* THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
* EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
* MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
*
* See the Mulan PSL v2 for more details.
***************************************************************************************/

#ifndef __UTILS_PROFILE_H__
#define __UTILS_PROFILE_H__

#include <common.h>

typedef enum {
  NEMU_PROFILE_CPU_EXEC_WINDOWS,
  NEMU_PROFILE_CPU_EXEC_US,
  NEMU_PROFILE_CPU_BASIC_BLOCKS,
  NEMU_PROFILE_CPU_BASIC_BLOCK_INST,
  NEMU_PROFILE_CPU_SINGLE_STEPS,
  NEMU_PROFILE_CPU_TB_STOP_STATE,
  NEMU_PROFILE_CPU_TB_STOP_CONTROL,
  NEMU_PROFILE_CPU_TB_STOP_SYSTEM,
  NEMU_PROFILE_CPU_TB_STOP_MEMORY_ORDER,
  NEMU_PROFILE_CPU_TB_STOP_IO_WRITE,
  NEMU_PROFILE_CPU_TB_STOP_STORE_CONSERVATIVE,
  NEMU_PROFILE_CPU_TB_STOP_LIMIT,
  NEMU_PROFILE_CPU_TB_STOP_CONTROL_FALLBACK,
  NEMU_PROFILE_CPU_TB_CONTINUE_BRANCH_TAKEN,
  NEMU_PROFILE_CPU_TB_CONTINUE_BRANCH_NOT_TAKEN,
  NEMU_PROFILE_CPU_TB_CONTINUE_JUMP_DIRECT,
  NEMU_PROFILE_CPU_TB_CONTINUE_JALR,
  NEMU_PROFILE_CPU_TB_CONTINUE_COMPRESSED_MISC,
  NEMU_PROFILE_CPU_TB_CONTINUE_FENCE,
  NEMU_PROFILE_CPU_TB_CONTINUE_CSR_READONLY,
  NEMU_PROFILE_CPU_TB_CONTINUE_CSR_SSTATUS_IMM_CLEAR,
  NEMU_PROFILE_CPU_TB_CONTINUE_CSR_SSTATUS_UNCHANGED,
  NEMU_PROFILE_CPU_TB_CONTINUE_CSR_SSTATUS_SIE_CLEAR,
  NEMU_PROFILE_CPU_TB_CONTINUE_CSR_TRAP_METADATA,
  NEMU_PROFILE_CPU_TB_CONTINUE_AMO,
  NEMU_PROFILE_CPU_TB_CONTINUE_AMO_LR,
  NEMU_PROFILE_CPU_TB_CONTINUE_AMO_SC,
  NEMU_PROFILE_CPU_TB_CONTINUE_AMO_SWAP,
  NEMU_PROFILE_CPU_TB_CONTINUE_AMO_ADD,
  NEMU_PROFILE_CPU_TB_CONTINUE_AMO_OTHER,
  NEMU_PROFILE_CPU_TB_STOP_FENCE_I,
  NEMU_PROFILE_CPU_TB_STOP_AMO,
  NEMU_PROFILE_CPU_TB_STOP_SYSTEM_CSR,
  NEMU_PROFILE_CPU_TB_STOP_SYSTEM_WFI,
  NEMU_PROFILE_CPU_TB_STOP_SYSTEM_SFENCE_VMA,
  NEMU_PROFILE_CPU_TB_STOP_SYSTEM_OTHER,
  NEMU_PROFILE_CPU_TB_STOP_AMO_LR,
  NEMU_PROFILE_CPU_TB_STOP_AMO_SC,
  NEMU_PROFILE_CPU_TB_STOP_AMO_SWAP,
  NEMU_PROFILE_CPU_TB_STOP_AMO_ADD,
  NEMU_PROFILE_CPU_TB_STOP_AMO_OTHER,
  NEMU_PROFILE_CPU_TB_STOP_SYSTEM_CSR_SSTATUS,
  NEMU_PROFILE_CPU_TB_STOP_SYSTEM_CSR_SIE,
  NEMU_PROFILE_CPU_TB_STOP_SYSTEM_CSR_STVEC,
  NEMU_PROFILE_CPU_TB_STOP_SYSTEM_CSR_SSCRATCH,
  NEMU_PROFILE_CPU_TB_STOP_SYSTEM_CSR_SEPC,
  NEMU_PROFILE_CPU_TB_STOP_SYSTEM_CSR_SCAUSE,
  NEMU_PROFILE_CPU_TB_STOP_SYSTEM_CSR_STVAL,
  NEMU_PROFILE_CPU_TB_STOP_SYSTEM_CSR_SIP,
  NEMU_PROFILE_CPU_TB_STOP_SYSTEM_CSR_SATP,
  NEMU_PROFILE_CPU_TB_STOP_SYSTEM_CSR_MSTATUS,
  NEMU_PROFILE_CPU_TB_STOP_SYSTEM_CSR_MIE,
  NEMU_PROFILE_CPU_TB_STOP_SYSTEM_CSR_MTVEC,
  NEMU_PROFILE_CPU_TB_STOP_SYSTEM_CSR_MSCRATCH,
  NEMU_PROFILE_CPU_TB_STOP_SYSTEM_CSR_MEPC,
  NEMU_PROFILE_CPU_TB_STOP_SYSTEM_CSR_MCAUSE,
  NEMU_PROFILE_CPU_TB_STOP_SYSTEM_CSR_MTVAL,
  NEMU_PROFILE_CPU_TB_STOP_SYSTEM_CSR_MIP,
  NEMU_PROFILE_CPU_TB_STOP_SYSTEM_CSR_MEDELEG,
  NEMU_PROFILE_CPU_TB_STOP_SYSTEM_CSR_MIDELEG,
  NEMU_PROFILE_CPU_TB_STOP_SYSTEM_CSR_MCOUNTEREN,
  NEMU_PROFILE_CPU_TB_STOP_SYSTEM_CSR_OTHER,
  NEMU_PROFILE_CPU_TB_STOP_SYSTEM_CSR_OP_CSRRW,
  NEMU_PROFILE_CPU_TB_STOP_SYSTEM_CSR_OP_CSRRS,
  NEMU_PROFILE_CPU_TB_STOP_SYSTEM_CSR_OP_CSRRC,
  NEMU_PROFILE_CPU_TB_STOP_SYSTEM_CSR_OP_CSRRWI,
  NEMU_PROFILE_CPU_TB_STOP_SYSTEM_CSR_OP_CSRRSI,
  NEMU_PROFILE_CPU_TB_STOP_SYSTEM_CSR_OP_CSRRCI,
  NEMU_PROFILE_CPU_TB_STOP_SYSTEM_CSR_OP_OTHER,
  NEMU_PROFILE_CPU_CSR_SSTATUS_WRITE_TOTAL,
  NEMU_PROFILE_CPU_CSR_SSTATUS_WRITE_CHANGED,
  NEMU_PROFILE_CPU_CSR_SSTATUS_WRITE_UNCHANGED,
  NEMU_PROFILE_CPU_CSR_SSTATUS_WRITE_DELTA_SIE,
  NEMU_PROFILE_CPU_CSR_SSTATUS_WRITE_DELTA_SPIE,
  NEMU_PROFILE_CPU_CSR_SSTATUS_WRITE_DELTA_SPP,
  NEMU_PROFILE_CPU_CSR_SSTATUS_WRITE_DELTA_FS,
  NEMU_PROFILE_CPU_CSR_SSTATUS_WRITE_DELTA_SUM,
  NEMU_PROFILE_CPU_CSR_SSTATUS_WRITE_DELTA_MXR,
  NEMU_PROFILE_CPU_CSR_SSTATUS_WRITE_DELTA_SXL_UXL,
  NEMU_PROFILE_CPU_CSR_SSTATUS_WRITE_DELTA_OTHER,
  NEMU_PROFILE_CPU_TB_STOP_SYSTEM_CSR_SSTATUS_DELTA_SIE_SET,
  NEMU_PROFILE_CPU_TB_STOP_SYSTEM_CSR_SSTATUS_DELTA_SIE_CLEAR,
  NEMU_PROFILE_CPU_TB_STOP_SYSTEM_CSR_SSTATUS_DELTA_SUM_SET,
  NEMU_PROFILE_CPU_TB_STOP_SYSTEM_CSR_SSTATUS_DELTA_SUM_CLEAR,
  NEMU_PROFILE_CPU_TB_STOP_SYSTEM_CSR_SSTATUS_DELTA_FS_TO_OFF,
  NEMU_PROFILE_CPU_TB_STOP_SYSTEM_CSR_SSTATUS_DELTA_FS_TO_INITIAL,
  NEMU_PROFILE_CPU_TB_STOP_SYSTEM_CSR_SSTATUS_DELTA_FS_TO_CLEAN,
  NEMU_PROFILE_CPU_TB_STOP_SYSTEM_CSR_SSTATUS_DELTA_FS_TO_DIRTY,
  NEMU_PROFILE_CPU_TB_STOP_SYSTEM_CSR_SSTATUS_DELTA_ONLY_SIE_SET,
  NEMU_PROFILE_CPU_TB_STOP_SYSTEM_CSR_SSTATUS_DELTA_ONLY_SIE_CLEAR,
  NEMU_PROFILE_CPU_TB_STOP_SYSTEM_CSR_SSTATUS_DELTA_ONLY_SUM_SET,
  NEMU_PROFILE_CPU_TB_STOP_SYSTEM_CSR_SSTATUS_DELTA_ONLY_SUM_CLEAR,
  NEMU_PROFILE_CPU_TB_STOP_SYSTEM_CSR_SSTATUS_DELTA_ONLY_FS,
  NEMU_PROFILE_CPU_TB_STOP_SYSTEM_CSR_SSTATUS_DELTA_OTHER_OR_MULTI,
  NEMU_PROFILE_CPU_STOP_DETAIL_ENABLED,
  NEMU_PROFILE_CPU_OPCODE_MIX_ENABLED,
  NEMU_PROFILE_CPU_OPCODE_RVC,
  NEMU_PROFILE_CPU_OPCODE_LOAD,
  NEMU_PROFILE_CPU_OPCODE_LOAD_FP,
  NEMU_PROFILE_CPU_OPCODE_MISC_MEM,
  NEMU_PROFILE_CPU_OPCODE_OP_IMM,
  NEMU_PROFILE_CPU_OPCODE_OP_IMM_32,
  NEMU_PROFILE_CPU_OPCODE_AUIPC,
  NEMU_PROFILE_CPU_OPCODE_STORE,
  NEMU_PROFILE_CPU_OPCODE_STORE_FP,
  NEMU_PROFILE_CPU_OPCODE_AMO,
  NEMU_PROFILE_CPU_OPCODE_OP,
  NEMU_PROFILE_CPU_OPCODE_OP_32,
  NEMU_PROFILE_CPU_OPCODE_FP,
  NEMU_PROFILE_CPU_OPCODE_BRANCH,
  NEMU_PROFILE_CPU_OPCODE_JALR,
  NEMU_PROFILE_CPU_OPCODE_JAL,
  NEMU_PROFILE_CPU_OPCODE_LUI,
  NEMU_PROFILE_CPU_OPCODE_SYSTEM,
  NEMU_PROFILE_CPU_OPCODE_OTHER,
  NEMU_PROFILE_CPU_DECODE_CACHE_LOOKUPS,
  NEMU_PROFILE_CPU_DECODE_CACHE_HITS,
  NEMU_PROFILE_CPU_DECODE_CACHE_MISSES,
  NEMU_PROFILE_CPU_DECODE_CACHE_FILLS,
  NEMU_PROFILE_CPU_DECODE_CACHE_HIT_RVC,
  NEMU_PROFILE_CPU_DECODE_CACHE_FILL_RVC,
  NEMU_PROFILE_CPU_RVC_DETAIL_ENABLED,
  NEMU_PROFILE_CPU_RVC_ADDI4SPN,
  NEMU_PROFILE_CPU_RVC_FLD,
  NEMU_PROFILE_CPU_RVC_LW,
  NEMU_PROFILE_CPU_RVC_LD,
  NEMU_PROFILE_CPU_RVC_FSD,
  NEMU_PROFILE_CPU_RVC_SW,
  NEMU_PROFILE_CPU_RVC_SD,
  NEMU_PROFILE_CPU_RVC_ADDI,
  NEMU_PROFILE_CPU_RVC_ADDIW,
  NEMU_PROFILE_CPU_RVC_LI,
  NEMU_PROFILE_CPU_RVC_ADDI16SP,
  NEMU_PROFILE_CPU_RVC_LUI,
  NEMU_PROFILE_CPU_RVC_SRLI,
  NEMU_PROFILE_CPU_RVC_SRAI,
  NEMU_PROFILE_CPU_RVC_ANDI,
  NEMU_PROFILE_CPU_RVC_SUB,
  NEMU_PROFILE_CPU_RVC_XOR,
  NEMU_PROFILE_CPU_RVC_OR,
  NEMU_PROFILE_CPU_RVC_AND,
  NEMU_PROFILE_CPU_RVC_SUBW,
  NEMU_PROFILE_CPU_RVC_ADDW,
  NEMU_PROFILE_CPU_RVC_J,
  NEMU_PROFILE_CPU_RVC_BEQZ,
  NEMU_PROFILE_CPU_RVC_BNEZ,
  NEMU_PROFILE_CPU_RVC_SLLI,
  NEMU_PROFILE_CPU_RVC_FLDSP,
  NEMU_PROFILE_CPU_RVC_LWSP,
  NEMU_PROFILE_CPU_RVC_LDSP,
  NEMU_PROFILE_CPU_RVC_JR,
  NEMU_PROFILE_CPU_RVC_MV,
  NEMU_PROFILE_CPU_RVC_EBREAK,
  NEMU_PROFILE_CPU_RVC_JALR,
  NEMU_PROFILE_CPU_RVC_ADD,
  NEMU_PROFILE_CPU_RVC_FSDSP,
  NEMU_PROFILE_CPU_RVC_SWSP,
  NEMU_PROFILE_CPU_RVC_SDSP,
  NEMU_PROFILE_CPU_RVC_OTHER,

  NEMU_PROFILE_DEVICE_UPDATE_CALLS,
  NEMU_PROFILE_DEVICE_UPDATE_RETIRED,
  NEMU_PROFILE_DEVICE_INTERVAL_SKIPS,
  NEMU_PROFILE_DEVICE_INTERVAL_FIRES,
  NEMU_PROFILE_DEVICE_TIME_SKIPS,
  NEMU_PROFILE_DEVICE_VISIBLE_TICKS,
  NEMU_PROFILE_DEVICE_INTERVAL_US,
  NEMU_PROFILE_DEVICE_VIRTIO_BLK_US,
  NEMU_PROFILE_DEVICE_VISIBLE_US,

  NEMU_PROFILE_CLINT_HOST_TIME_READS,

  NEMU_PROFILE_SERIAL_TX_FLUSHES,
  NEMU_PROFILE_SERIAL_TX_BYTES,
  NEMU_PROFILE_SERIAL_TX_FLUSH_US,
  NEMU_PROFILE_SERIAL_RX_POLLS,
  NEMU_PROFILE_SERIAL_RX_BYTES,

  NEMU_PROFILE_VADDR_IFETCH_CALLS,
  NEMU_PROFILE_VADDR_IFETCH_WIDE_ATTEMPTS,
  NEMU_PROFILE_VADDR_IFETCH_WIDE_HITS,
  NEMU_PROFILE_VADDR_IFETCH_WIDE_DISABLED,
  NEMU_PROFILE_VADDR_IFETCH_WIDE_CROSS_PAGE,
  NEMU_PROFILE_VADDR_IFETCH_WIDE_FAULTS,
  NEMU_PROFILE_VADDR_IFETCH_WIDE_PADDR_FALLBACKS,
  NEMU_PROFILE_VADDR_IFETCH_CACHE_HITS,
  NEMU_PROFILE_VADDR_IFETCH_CACHE_MISSES,
  NEMU_PROFILE_VADDR_IFETCH_CACHE_FILLS,
  NEMU_PROFILE_VADDR_IFETCH_CACHE_FLUSHES,
  NEMU_PROFILE_VADDR_IFETCH_CACHE_INVALIDATES,
  NEMU_PROFILE_VADDR_CROSS_PAGE_READS,
  NEMU_PROFILE_VADDR_CROSS_PAGE_WRITES,
  NEMU_PROFILE_VADDR_HOST_FAST_READS,
  NEMU_PROFILE_VADDR_HOST_FAST_WRITES,
  NEMU_PROFILE_VADDR_PADDR_FALLBACK_READS,
  NEMU_PROFILE_VADDR_PADDR_FALLBACK_WRITES,
  NEMU_PROFILE_VADDR_FAULTS,

  NEMU_PROFILE_MMU_TLB_DISABLED,
  NEMU_PROFILE_MMU_TLB_LOOKUPS,
  NEMU_PROFILE_MMU_TLB_HITS,
  NEMU_PROFILE_MMU_TLB_MISSES,
  NEMU_PROFILE_MMU_TLB_FILLS,
  NEMU_PROFILE_MMU_TLB_FLUSH_FULL,
  NEMU_PROFILE_MMU_TLB_FLUSH_SELECTIVE,
  NEMU_PROFILE_MMU_WALKS,
  NEMU_PROFILE_MMU_PTE_READS,
  NEMU_PROFILE_MMU_PTE_UPDATES,
  NEMU_PROFILE_MMU_FAULTS,

  NEMU_PROFILE_PADDR_PMEM_READS,
  NEMU_PROFILE_PADDR_PMEM_READ_BYTES,
  NEMU_PROFILE_PADDR_PMEM_WRITES,
  NEMU_PROFILE_PADDR_PMEM_WRITE_BYTES,
  NEMU_PROFILE_PADDR_CLINT_READS,
  NEMU_PROFILE_PADDR_CLINT_WRITES,
  NEMU_PROFILE_PADDR_PLIC_READS,
  NEMU_PROFILE_PADDR_PLIC_WRITES,
  NEMU_PROFILE_PADDR_MMIO_READS,
  NEMU_PROFILE_PADDR_MMIO_WRITES,
  NEMU_PROFILE_PADDR_DMA_WRITES,
  NEMU_PROFILE_PADDR_DMA_WRITE_BYTES,

  NEMU_PROFILE_COUNTER__COUNT,
} NemuProfileCounter;

void nemu_profile_dump(uint64_t guest_inst, uint64_t total_exec_us);

extern uint64_t nemu_profile_counters[NEMU_PROFILE_COUNTER__COUNT];
extern bool nemu_profile_is_enabled;
extern bool nemu_profile_opcode_mix_is_enabled;
extern bool nemu_profile_stop_detail_is_enabled;
extern bool nemu_profile_decode_cache_is_enabled;
extern bool nemu_profile_rvc_detail_is_enabled;

static inline void nemu_profile_count(NemuProfileCounter counter,
    uint64_t amount) {
  if (counter >= 0 && counter < NEMU_PROFILE_COUNTER__COUNT) {
    nemu_profile_counters[counter] += amount;
  }
}

static inline bool nemu_profile_enabled(void) {
#ifdef CONFIG_TARGET_AM
  return false;
#else
  return unlikely(nemu_profile_is_enabled);
#endif
}

static inline void nemu_profile_count_if(NemuProfileCounter counter,
    uint64_t amount) {
  if (nemu_profile_enabled()) {
    nemu_profile_count(counter, amount);
  }
}

static inline bool nemu_profile_opcode_mix_enabled(void) {
#ifdef CONFIG_TARGET_AM
  return false;
#else
  return unlikely(nemu_profile_opcode_mix_is_enabled);
#endif
}

static inline bool nemu_profile_stop_detail_enabled(void) {
#ifdef CONFIG_TARGET_AM
  return false;
#else
  return unlikely(nemu_profile_stop_detail_is_enabled);
#endif
}

static inline bool nemu_profile_decode_cache_enabled(void) {
#ifdef CONFIG_TARGET_AM
  return false;
#else
  return unlikely(nemu_profile_decode_cache_is_enabled);
#endif
}

static inline bool nemu_profile_rvc_detail_enabled(void) {
#ifdef CONFIG_TARGET_AM
  return false;
#else
  return unlikely(nemu_profile_rvc_detail_is_enabled);
#endif
}

#endif
